### ISSUE TITLE
Improve Gradle-related Kotlin code

### ISSUE THREAD

**Issue by MaciejG604** [VirtusLab/git-machete-intellij-plugin#1004]
After migrating the gradle scripts to Kotlin there are some issues that need to be resolved:

- [x] Find a way to use version catalog aliases in helpers' code in buildSrc/
(one way to do it would be to put the aliases into extra properties of the project in buildSrc)
- [x] Unify plugins' notations in `libraries` and `plugins` in libs.version.toml:
  * [x] the versions shared with the `[plugins]` sections should be extracted to `[versions]` section to avoid discrepancies
  * [x] or maybe the `[plugins]` section can be removed completely in favor of the newly-added `[libraries]`?
  * [x] extra care should be taken to retain `@pins` on certain plugins, as done in `[plugins]` currently (so that they're NOT auto-updated by `gradle versionCatalogUpdate`)
  * [x] a comment would be useful why plugins in `[libraries]` are needed in the first place and/or a reference to a blogpost describing this technique
- [x] Remove code that's marked as Deprecated from `CheckerFrameworkConfigurator::applySubtypingChecker`, then [revert `kotlinOptions.allWarningsAsErrors = true` in `buildSrc/build.gradle.kts`](https://github.com/VirtusLab/git-machete-intellij-plugin/pull/989#discussion_r929939862)
- [x] Refactor `IntellijVersionHelper` so that there are no unsafe typecasts: preferably extract a data class to keep the IntelliJ versions retrieved from properties file, to avoid using string keys
- [x] Switch all classes in buildSrc to Kotlin
- [x] Remove all remaining support for Groovy from Gradle code (mostly Spotless)
- [x] Check if it's possible to keep `build.gradle.kts` files [formatted with Spotless](https://github.com/diffplug/spotless/tree/main/plugin-gradle#kotlin) (and not just files in buildSrc/) &mdash; see `kotlinGradle { ... }`
- [x] Fix spotless for Kotlin so that it launches automatically with `./gradlew build`
- [x] Fix Gradle warning in `:buildSrc:compileKotlin` task: `'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version`
- [x] Check if there is any built-in way in Kotlin to use static identifiers for projects: something like `api(project(branchLayout.api))`. Probably no point in defining them explicitly if they aren't available OOTB => NO
- [x] Check if it's possible to replace `BuildUtils.foo(project)` calls with just `foo()` (probably an extension method on `Project` would be needed) => YES
- [x] Rewrite the latter half of `UpdateEapBuildNumber#checkForEapWithBuildNumberHigherThan` to use Kotlin regex API
- [x] Consider un-hardcoding names of `IntellijVersions` properties by using `.name`: https://kotlinlang.org/docs/reflection.html#property-references

**Comment by PawelLipski** [comment]
(@MaciejG604  checkboxes FTW ☝🏻 )

**Comment by PawelLipski** [comment]
@MaciejG604 pls tick off once you **start work** on the given point. This will prevent doubling the efforts in case someone else would like to pick a subtask.

**Comment by MaciejG604** [comment]
I don't know if un-hardcoding names of IntellijVersions properties can be done while still keeping all the type guarantees. It is so becuase the class stores not only Strings (nullable and not-nullable) but also a List<String>. 
It was not hardcoded before using a Map<String, Any>, but the types could not be checked by the compiler.

**Comment by PawelLipski** [comment]
Ouch, sorry... I pointed to the wrong class. I meant unhardcoding keys in the dict used in `com.virtuslab.gitmachete.buildsrc.IntellijVersionHelper#resolveIntelliJVersions` ‼️

**Comment by MaciejG604** [comment]
Also related but can't link as there's a limit of 10 PRs linked:
#1035, #1038
