### ISSUE TITLE
Where do Gradle docs point when looking for a way to write code reusable between subprojects?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1028]
In case of:
1. Groovy
2. Groovy->Kotlin migration
3. Kotlin

My suspicion is that:
1. `ext { foo = { -> ... } }`
2. (dunno)
3. `buildSrc/`

To be verified. If anything is missing/misleading/confusing in the official Gradle docs/easily Googlable blogposts, let's consider publishing a blogpost of our own. Let's use it for not-so-subtle marketing for this project, as was with e.g. [Nifty Docker tricks for your CI](https://medium.com/virtuslab/nifty-docker-tricks-for-your-ci-vol-1-c4a36d2192ea) and the CLI.

**Comment by MaciejG604** [comment]
[Use buildSrc to separate imperative logic](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources)
[Moving build logic into custom plugins and putting them in buildSrc/](https://docs.gradle.org/current/userguide/authoring_maintainable_build_scripts.html#sec:avoid_imperative_logic_in_scripts)
[Moving build logic into custom plugins and putting them in buildSrc/](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins)
[Precompiled script plugins (also mentions buildSrc/)](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins)
[Using allprojects and subprojects blocks - mentioned as DISCOURAGED](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration)

Gradle docsdo not differentaite between DSLs and mostly point to writing custom plugins and precompiled script plugins, also frequently mentions buildSrc as the directory to put those plugins into. Allprojects and subprojects blocks are mentioned as DISCOURAGED, I think the same applies to using extra properties for anything more than just sharing variables.

**Comment by PawelLipski** [comment]
Okay! so it seems that Gradle docs are pretty clear in this regard. Not really much space for a blog post... closing the issue.
