### ISSUE TITLE
Further migrate the build logic to code in buildSrc/src/main/

### ISSUE THREAD

**Issue by MaciejG604** [VirtusLab/git-machete-intellij-plugin#1031]
In the issues #750, #687 and also #1004 parts of the gradle build scripts have been moved to the buildSrc directory.
The code that has been extracted consists mostly of plugin application and/or configuration. Parts of the root (and maybe others as well) build.gradle.kts could still be migrated to buildSrc, e.g. configuration of `JavaLibraryPlugin`, `GrgitPlugin`, `IntelliJPlugin` and also configuration of UiTests.

Another thing to consider is rewriting Spotless and VersionCatalogUpdate configuration as a precompiled script so they could be used also in buildSrc/build.gradle.kts. From what I've tried code in buildSrc/src/ can't be used in buildSrc/build.gradle.kts as it is built after the script. 

Using exisitng code in buildSrc/ consider further build logic migration out of the build scripts.

**Comment by PawelLipski** [comment]
Only `JavaLibraryPlugin` config left... lemme extract a separate task
