### ISSUE TITLE
Agree one name of our product for end user

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#104]
In different places we are using different name of our product (`git-machete`, `Git Machete`, `Git-Machete`, and so on) esp. in logging messages and exceptions. We must agree one name and change to this name every end user's message.

**Comment by PawelLipski** [comment]
Decided on `Git Machete` (Title Case, as recommended in https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html)
