### ISSUE TITLE
Once a version which does NOT support IntelliJ X.Y is released, is it still possible to install an old version in IntelliJ X.Y?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1084]
In particular, is it still possible to install 1.x.y version of this plugin in e.g. IntelliJ 2019.3? 

This question is pretty important wrt. publishing 3.0.0: if after publishing 3.0.0 (which is only going to support IntelliJs 2022.1 onwards) it's still possible to install 2.x.y on 2021.3 and earlier, then maybe we shouldn't postpone the release of 3.0.0 so much 🤔

**Comment by mkondratek** [comment]
Good question and I was wondering about it recently too. I will try do install some older intellij version and see what are the results in the marketplace.

**Comment by mkondratek** [comment]
Nice. Older IntelliJ versions can be easily downloaded from **[this place](https://www.jetbrains.com/idea/download/other.html)**.

Now, having:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/19799111/186635759-ea1c6e1d-f789-4038-b769-5b26a24546a5.png">

...and going to the marketplace...

![image](https://user-images.githubusercontent.com/19799111/186636222-d2331064-dcdd-4b14-b483-8e10e2bb2596.png)

...not there. [JetBrains Marketplace](https://plugins.jetbrains.com/)...

<img width="989" alt="image" src="https://user-images.githubusercontent.com/19799111/186636572-42f5bdc4-2330-44c7-a69f-a29b96330edf.png">

...we can see that [**Git Machete plugin**](https://plugins.jetbrains.com/plugin/14221-git-machete) in version 1.3.0 (which is the latest supporting intellij 201 according to [our versions refrerence](https://plugins.jetbrains.com/plugin/14221-git-machete/versions/stable/170574)).

I ve installed it and it works just fine.

**Comment by mkondratek** [comment]
So, yes. We indeed can care less about supporting the older intellij versions. _Some_ Git Machete plugin version still remains available for them.

**Comment by mkondratek** [comment]
Also note that the plugin version reference page show a chart with downloads of a specific version by time. For example we can see that there was a single download of plugin 0.8.0 in March 2022. 🤣

**Comment by mkondratek** [comment]
Another note. In the same page there is an option to **hide** a plugin version. I tested it too. It makes a version unavailable to download. Hiding 1.3.0 resulted in version 1.2.1 - still, the latest supporting intellij 201 that is not hidden.

**Comment by PawelLipski** [comment]
:benissimo:

Okay! soooo given that 2022.3 will only come out in November/December probably (there's late August and still no 223-EAP-SNAPSHOT, only some stray 223-EAP-CANDIDATE-SNAPSHOT), probably it makes sense **not** to wait for 2022.3 to come out with publishing 3.0.0 🤔

**Comment by PawelLipski** [comment]
Actually! as an output of this task, could you update a comment in IntellijVersions.kt, around `earliestSupportedMajor`? So that this knowledge isn't lost in the depths of GitHub issues
