### ISSUE TITLE
Change-log plugin does not add a new line at the end of CHANGE-NOTES.md when using `./gradlew patchChangelog`

### ISSUE THREAD

**Issue by MaciejG604** [VirtusLab/git-machete-intellij-plugin#1093]
For now CHANGE-NOTES.md will be excluded from git-hook checking new line at eof.
I will report an issue in change-log-plugin.

**Comment by MaciejG604** [comment]
[Change-log issue](https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1093)

**Comment by PawelLipski** [comment]
Will be fixed soon with a new release of the changelog-plugin. Nothing to be done on our side, just bump the version.
