### ISSUE TITLE
Cache the results of `machete-status-branch` hook based ALSO on the hook contents

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1108]
See `com.virtuslab.gitmachete.backend.impl.hooks.StatusBranchHookExecutor#hookOutputByBranchNameAndCommitHash` for the current caching rules... I'd add hook content as well to be extra-protected against stale cache issues

**Comment by PawelLipski** [comment]
Note that the values of `com.virtuslab.gitmachete.backend.impl.hooks.StatusBranchHookExecutor#hookOutputByBranchNameAndCommitHash` are hook **outputs** (the stdouts from execution), not hook **contents** (bytes of the hook script itself). What I propose in this issue to add hook content to the **key**. Values are to remain unchanged.

> Is the desired behaviour to not cache the None hook content, so as to rerun the hook in a subsequent enquiry, for obtaining Some(value)?

I'd leave the logic in `com.virtuslab.gitmachete.backend.impl.hooks.StatusBranchHookExecutor#deriveHookOutputFor` as is. `None` value suggests that the hook execution failed for the given input, and is hence **not** to be rerun.

**Comment by PawelLipski** [comment]
One more thing, as the hook contents might theoretically be quite large, it might be better to use a hash (like MD5 or whatever) instead the full contents.

**Comment by vzmerr** [comment]
Got it: you mean the hashed content of the `hookFile` itself
