### ISSUE TITLE
Add actions to move to parent/next/previous branch

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1120]
Similar spirit to `git machete go up/next/prev`.

They need to be available via keyboard shortcuts (now that #645 turned out to be resolved).

This will make it possible to simulate `git machete traverse` entirely from keyboard (with other shortcuts assigned to Rebase, Push etc. actions).

**Comment by vzmerr** [comment]
>simulate git machete traverse entirely from keyboard

So when using the keyboard shortcut to traverse, this should highlight the next branch and then show a dialogue for pulling from origin, pushing from origin, or rebasing onto root?

Because `go up/next/previous` actually checks out, which `traverse` doesn't.

**Comment by PawelLipski** [comment]
> So when using the keyboard shortcut to traverse, this should highlight the next branch and then show a dialogue for pulling from origin, pushing from origin, or rebasing onto root?

As for now, such functionality is beyond the scope of the task... such automation is to be considered, but it might be too much for this plugin. Let's first try with actions to switch between the branches from keyboard.

> Because go up/next/previous actually checks out, which traverse doesn't.

`git machete traverse` **does** check out the branches! Once rebase/push/pull for a  branch is complete, it switches to the next branch that requires any action
