### ISSUE TITLE
After upgrade of Spotless, ktlint prints a lot of spam about `disabled_rules`; migration to `ktlint_disabled_rules` not possible

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1129]
```
> Task :spotlessKotlinGradle
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
Property 'disabled_rules' is deprecated: Rename property 'disabled_rules' to 'ktlint_disabled_rules' in all '.editorconfig' files.
```

Update of spotless from 6.10 to 6.11 in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1122/ also bumped ktlint to 0.47.1; [0.47.0](https://github.com/pinterest/ktlint/releases/tag/0.47.0) deprecated `disabled_rules`.

Unfortunately, `ktlint_disabled_rules` seem to be ignored in our usage (`ktlint().editorConfigOverride(...)`), so the migration leads to build failing on the rules being still enabled :/

It's a choice between spam (if `disabled_rules` present) or outright failure (if absent) :/

I hope it'll _get itself sorted_ with subsequent releases of ktlint/spotless... but let's revisit if it doesn't in a few weeks.

**Comment by PawelLipski** [comment]
Re-assigning to @LukaszKontowski as well

**Comment by LukaszKontowski** [comment]
@PawelLipski how can I reproduce this output spamming? Tried to do some _bad style_ formatting on `.kt` files, but:
```
% ./gradlew :spotlessKotlinGradle

BUILD SUCCESSFUL in 2s
17 actionable tasks: 17 up-to-date
```
no spam was produced

**Comment by PawelLipski** [comment]
Bump Spotless to 6.11 in version catalog 🤔

**Comment by PawelLipski** [comment]
I've downgraded to 6.10 to get rid of the spam

**Comment by PawelLipski** [comment]
Wow okay... and for your local `6.11.1-SNAPSHOT`, which version of ktlint has been used, 0.47.x?

Anyway, looks that we can just wait it out until Spotless Gradle plugin 6.11.1 (or 6.12.0, whichever comes first) is published

**Comment by LukaszKontowski** [comment]
> Wow okay... and for your local `6.11.1-SNAPSHOT`, which version of ktlint has been used, 0.47.x?

yes, 0.47.x - properly

**Comment by PawelLipski** [comment]
Un-assigning from you then, thx

**Comment by PawelLipski** [comment]
Resolved some time ago with https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1502/
