### ISSUE TITLE
What's specifically understood by SemVer of plugin updates, can we enable it?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1140]
https://plugins.jetbrains.com/plugin/14221-git-machete -> General Information:

![image](https://user-images.githubusercontent.com/3383210/191251499-b4554bc3-1b02-4979-9948-eedbaed51221.png)

To be checked if JetBrains' understanding is compatible with ours, as documented in CONTRIBUTING.md + if this setting can be enabled via gradle-intellij-plugin

**Comment by LukaszKontowski** [comment]
🤔 I cannot find the SemVer Only under https://plugins.jetbrains.com/plugin/14221-git-machete ... Nor the `General Information` heading. @PawelLipski - can you paste a snippet with whole screen? Maybe I missed it?

**Comment by PawelLipski** [comment]
Whoops I forgot it's only visible to Plugin Developers, as understood by Marketplace... pls create your account on Marketplace and send me the login, I'll add you

**Comment by LukaszKontowski** [comment]
Sure, just created it:
username:
LukaszKontowski
e-mail:
kontowski.lukasz@gmail.com

**Comment by PawelLipski** [comment]
Okay see now

**Comment by LukaszKontowski** [comment]
1. JetBrains' understanding: https://plugins.jetbrains.com/docs/marketplace/semver.html
They point to the https://semver.org/ as the source of truth. So, the understanding should be the same as ours:
> We follow [Semantic versioning](https://semver.org/) for the plugin releases:

2. I'm checking "if this setting can be enabled via gradle-intellij-plugin". For sure we can enable it manually anyway.

**Comment by PawelLipski** [comment]
1.
> As of now, the main benefit to turn on the SemVer option is the ability to upload an update with minor fixes without changing the information on the plugin page.

Weeeird as it's basically available right now 🤔 every time we've uploaded a new update (i.e. on each `master` build) in the last ~2 years, we haven't updated the information on the plugin page really

**Comment by PawelLipski** [comment]
It looks that the versioning only matters if any of the basic metadata (name, URL, vendor, description) is changed... which is very rare in our case. We've only changed the description in the last 2 years once:

![image](https://user-images.githubusercontent.com/3383210/192318107-f928eb8b-a515-4c6c-936d-4698b236fa85.png)

The other data is likely unchanged since 2020.

**Comment by PawelLipski** [comment]
So in a nutshell... it seems mostly irrelevant to our plugin.

**Comment by LukaszKontowski** [comment]
Ok, do we close this issue?

**Comment by PawelLipski** [comment]
:yes:
