### ISSUE TITLE
Prevent merging branches to `master` accidentally

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1144]
Only pass a build of a PR to `master` if the head branch is `develop` or `hotfix/*`. 
See e.g. https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1143

**Comment by LukaszKontowski** [comment]
https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1143/ - the reason of this issue is to make the build fail for such PRs ?

**Comment by PawelLipski** [comment]
:yes: exactly
