### ISSUE TITLE
Do we have a company 1password/LastPass account?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1163]
As for now, I'm keeping all git-machete/git-machete-intellij-plugin creds in my personal LastPass... which is a very `bus-factor==1` approach. Better to have some shared vault. Let's first research if we have anything ready company-wide.

**Comment by LukaszKontowski** [comment]
> Let's first research if we have anything ready company-wide.

@PawelLipski - so, any tool could be OK or just 1password/LastPass? There are also other tools, for example [Vault](https://www.vaultproject.io/)...

**Comment by PawelLipski** [comment]
Vault is also okay, as long as we've got sth set up company-wide (although I'd rather expect LastPass to be readily available, if anything). If nothing is ready OOTB... let's think what's gonna be the best solution (esp. so that we don't need to pay xD)

**Comment by LukaszKontowski** [comment]
We have 1password - I asked @wardi for help and now I'm waiting. I will update this issue as soon as I have something concrete.

**Comment by LukaszKontowski** [comment]
https://virtuslab.atlassian.net/servicedesk/customer/portal/1/SUP-1707 created

**Comment by LukaszKontowski** [comment]
Do we close this one?

**Comment by PawelLipski** [comment]
Done now!
