### ISSUE TITLE
Drop support for 2022.1: override `getActionUpdateThread` in our actions

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1171]
![image](https://user-images.githubusercontent.com/3383210/192326557-9ab6b7f1-1314-4d0e-807b-67205eb7807b.png)

As for now, the default seems to be `com.intellij.openapi.actionSystem.ActionUpdateThread#OLD_EDT`:

![image](https://user-images.githubusercontent.com/3383210/192326750-d695b4ce-9580-4a34-a8d1-c2bfdfb14cc8.png)

This is deprecated, the plugins should migrate to select either `BGT` or `EDT`.

To be checked when `ActionUpdateThread` was added/how it affects our IDEA compatibility.

**Comment by PawelLipski** [comment]
Okay, so let's leave as is for the moment, to be done as a part of #859. Marking as `intellij-support`

**Comment by PawelLipski** [comment]
Hmm.... actually, _break compatibility_... in what specific sense? as in, what's gonna be the error from `gradle runPluginVerifier`?

I'd bet that you still can define the `getActionUpdateThread` (in 2022.1, it just won't be an overridden method). Or are `ActionUpdateThread` constants missing in 2022.1 as well? (that would be more of a problem)

**Comment by MaciejG604** [comment]
Constants are missing :(

**Comment by PawelLipski** [comment]
☹️
