### ISSUE TITLE
Can we get the ability to rename a branch?

### ISSUE THREAD

**Issue by radeusgd** [VirtusLab/git-machete-intellij-plugin#1183]
From time to time I have the need to rename a branch.

One of the use-cases I encounter is that I create an experimental branch, but then create a task associated with it (in my case in Pivotal Tracker) and for the tool to be able to automatically correlate my branch with the task, I need to append the task number as a suffix of the branch name. So I need to rename the branch to include this new number.

My current course of action is `git checkout -b new_branch_name` followed by updating the machete file, replacing the old name with the new one.

However this results in:
![image](https://user-images.githubusercontent.com/1436948/192779225-5e41a7d8-b87a-4a67-a9a5-edc2fbb8f2be.png)

That of course makes sense, but then it forces me to add a manual override: `git machete fork-point --override-to-parent new_branch_name`.

It is of course doable, but then I need to go out of the GUI. It would be nice to perform a rename without hassle directly from IntelliJ :)

**Comment by mkondratek** [comment]
+1. For me, sometimes I make typos and want to fix them

**Comment by PawelLipski** [comment]
Actually, +1 myself, I thought of that as well ;D I usually do `git branch -m <new-name>`, then let the CLI/plugin slide out the old invalid branch name, and then re-add the renamed branch. Still, a `git machete rename` and an action to rename a branch would be useful.

**Comment by PawelLipski** [comment]
☝🏻 for the CLI counterpart
