### ISSUE TITLE
Mac OS - actions on branch not displayed after "right click" on touchbar

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/git-machete-intellij-plugin#1190]
Actions on branch are not displayed after "right click" on touchbar (Ctrl + click). See how it should work: https://github.com/VirtusLab/git-machete-intellij-plugin#scenario-1-review
After `Ctrl + click` on the branch name - nothing is displayed. 

There is **no** similar problem when using a proper mouse on the Mac laptop (where you have a real right-click). This should work the same way as with a right-click using a mouse.

Ctrl + click works fine in other places in IntelliJ IDEA

Appears for:
MacBook Apple M1 Pro 16-inch 2021

**Comment by PawelLipski** [comment]
Compared to the relatively minor issues we've been fixing recentely, this is quite SEVERE ☹️

**Comment by PawelLipski** [comment]
Btw @mkondratek you would've probably spotted this... do you observe the same problem? or you don't use touchbar?

**Comment by LukaszKontowski** [comment]
There are some similar issues reported on the web with some explanations and potential solutions:
https://github.com/zaproxy/zaproxy/issues/131
https://stackoverflow.com/questions/2972512/how-to-detect-right-click-event-for-mac-os

Looks like `SwingUtilities.isRightMouseButton(e)` could not work for `Ctrl + click` on MacBooks

**Comment by mkondratek** [comment]
But I see that ctrl+click really works like right click (which is a suprise to me) and probably we should provide the similar beavior within git machete tab.

(a "standard" right click on touchpad works as expected)

**Comment by LukaszKontowski** [comment]
so, I'm doing it for a long time (for me two-fingers click is new)

**Comment by mkondratek** [comment]
For me it's strange bc Ctrl + click  requires two hands  xd  but it seems we should get it working too

**Comment by PawelLipski** [comment]
Wow such a _cultural enrichment_ happening on this issue 😅
