### ISSUE TITLE
The text of `Cannot pull anymore` notification is truncated, no way to expand

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1198]
![image](https://user-images.githubusercontent.com/3383210/193420284-5bc9243e-c36a-4be2-b95c-02af7dda0982.png)

To be researched whether there are other places that are (potentially) affected by the same problem. Ideally, to be prevented automatically somehow 😅

**Comment by mkondratek** [comment]
oh 🕵️‍♂️
