### ISSUE TITLE
False positive: "Some branches listed in machete file do not exist: ..."

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/git-machete-intellij-plugin#1204]
Reproduce steps:
- create branch `A`
- add branch `A` to the machete file
- remove branch `A` locally with `git branch -d A` in the terminal / command line
- open IntelliJ IDEA
- remove branch `A` from the machete file
- open the `Git Machete` window in IntelliJ ...
- The "Some branches listed in machete file do not exist: ..." warning is displayed (which is a false positive)
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/49597713/193530203-0ca8813a-abdd-44a8-8f6c-3bfe4fb0320b.png">

However, after some time the warning does not appear anymore. It looks like the update in IDE is delayed.

**Comment by mkondratek** [comment]
numbered list would be more useful while describing steps 😉 

step `remove branch A from the machete file` - you mean remove it from outside (terminal, not from IDE)?

**Comment by LukaszKontowski** [comment]
> step `remove branch A from the machete file` - you mean remove it from outside (terminal, not from IDE)?

I removed it using the IDE editor.

**Comment by mkondratek** [comment]
oh, interesting. and did you save the file (cmd+s/smth)? b/c if you didnt it can still be the same case (vfs)

**Comment by LukaszKontowski** [comment]
No, I did not save it additionally. But it has been changed without saving in IDE from my side (checked using `cat` on this file from terminal).

**Comment by mkondratek** [comment]
ok, can it be saved on the computer file system but remain not saved in ide vfs? 😆 does the issue occur when you save the file from ide?

**Comment by LukaszKontowski** [comment]
> ok, can it be saved on the computer file system but remain not saved in ide vfs? 😆 does the issue occur when you save the file from ide?

Looks like a volatile bug. I tried to reproduce it now, but this time no false warning was displayed. 🤔

**Comment by mkondratek** [comment]
![image](https://user-images.githubusercontent.com/19799111/193560010-e801d25c-fb0a-42b2-bfca-247f47f1d578.png)

**Comment by LukaszKontowski** [comment]
Ok, maybe this was a one-time error not worth working on.

**Comment by PawelLipski** [comment]
Huh sounds like a race condition ☹️ let's keep the issue around, but probably not worth starting work on immediately

**Comment by PawelLipski** [comment]
Rel: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1227, this might be a proper fix, actually

**Comment by PawelLipski** [comment]
Probably permanently solved by #1292 anyway... closing, to be reopened if ever re-occurs (doubtful)
