### ISSUE TITLE
Use new ArchUnit 1.0.0 features/improvements in our tests

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1212]
Potentially relevant changes:

> Accesses from inside of lambdas are now correctly detected. Before, the origin was set as a synthetic method like lambda$xxx$123 instead. JavaAccess can now be queried for isDeclaredInLambda() to distinguish this from an access outside of a lambda (see https://github.com/TNG/ArchUnit/pull/847; thanks a lot to @oberprah, @FrederikFinckh)

> New methods codeUnits().should().onlyBeCalled().by{Classes/Methods/...}That(..)

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1211#discussion_r986583686_

**Comment by mkondratek** [comment]
Oh, I was just wondering whats wrong now

**Comment by PawelLipski** [comment]
I went through all ArchUnit tests, can't see any place where we'd clearly benefit from new APIs. Closing
