### ISSUE TITLE
'Checkout and rebase to parent' actually hard resets to parent

### ISSUE THREAD

**Issue by vzmerr** [VirtusLab/git-machete-intellij-plugin#1214]
## Bug description

1. Please create a local copy of the [following](https://github.com/VirtusLab/git-machete-intellij-plugin/tree/reset-bug-instead-of-rebase) branch which is out of sync with `develop`.
2. Slide in this branch under `develop`.
3. checkout another branch.
4. right click on your local copy of `reset-bug-instead-of-rebase` in the machete tab and choose `Checkout and Sync to parent by rebase`.
5. if there are conflicts, please resolve them by using `git add conflict\file\address` and `git rebase --continue` in the Terminal.
6. After the successful rebase, please take a look at the log: The commit history is the exact same as the develop. In other words, rebase has behaved the same as `git reset --hard develop` on the `reset-bug-instead-of-rebase` branch.

It is already verified that `git rebase develop` on the same commit history, behaves correctly with no problem.

**Comment by vzmerr** [comment]
> for me the following appeared after step 4

So this is indeed a bug. What happens when you press cancel? does it recover your pre-rebase commit history?

**Comment by mkondratek** [comment]
no change to the history happens to this step. the rebase would make the changes.

**Comment by vzmerr** [comment]
ok, it's good that at least by cancelling you can prevent the reset.

**Comment by PawelLipski** [comment]
Hmmm so for clarity... 

> for me the following appeared after step 4
> > So this is indeed a bug. 

Does it mean that for you @vzmerr, such warning dialog (it's from git4idea btw, not ours) does NOT appear? 🤔

**Comment by PawelLipski** [comment]
Bump ☝🏻

**Comment by vzmerr** [comment]
> Bump ☝🏻

it does.

**Comment by PawelLipski** [comment]
Hmmm okay... so given that the user is warned about exactly what's gonna happen... can we consider the issue closed?

**Comment by PawelLipski** [comment]
Assuming that can be closed
