### ISSUE TITLE
Replace calls to `str.trim().isEmpty()` with `str.isBlank()`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1218]
The former was needed to keep compatible with Java 8, which doesn't have `String#isBlank`.

**Comment by TomasVitkovic** [comment]
Hello, can you please assign this issue to me?

**Comment by PawelLipski** [comment]
Sure, why not! Pls remember to open a PR to `develop` (not `master`). In case of doubts, check [CONTRIBUTING.md](CONTRIBUTING.md) or ask me here on this issue

**Comment by ishu-thakur** [comment]
Hi @PawelLipski can i raise the PR for this to develop branch as i am done fixing it ? even tho it is assigned to @TomasVitkovic.

**Comment by PawelLipski** [comment]
Haha what a _race_ 🐎 ;D okay since @ishu-thakur you're done, there's no point in @TomasVitkovic duplicating the work... wanna get another issue instead? ;)

**Comment by PawelLipski** [comment]
Ok pls check #757 then 🕵🏻
