### ISSUE TITLE
Issues opened via error submitter have `com.intellij.diagnostic.IdeaReportingEvent$TextBasedThrowable` as title

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1223]
See #1215. I'd rather expect sth like `java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.isDirectory()" because "file" is null` as the title.

FWIW, I did some quick debug on branch `debug/1215-submitter-title` but reached no conclusion. I can't see where the `TextBasedThrowable` is even coming from 🤔 

As a part of this task, add a test that would've capture the issue.

**Comment by LukaszKontowski** [comment]
> I can't see where the `TextBasedThrowable` is even coming from 🤔

It comes from [IdeaReportingEvent](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/diagnostic/IdeaReportingEvent.java) from IntelliJ repository (JFYI).
