### ISSUE TITLE
`IBranchLayout#equals` isn't a valid `equals` method

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1260]
It will be actually invoked in places like `com.virtuslab.gitmachete.frontend.ui.impl.RediscoverSuggester#isDiscoveredBranchLayoutEquivalentToCurrent` where it's directly called (`return discoveredBranchLayout.equals(currentBranchLayout)`). It won't work, however, for calls like `exists` or `contains` on collections that use `boolean equals(Object other)` and not `boolean equals(IBranchLayout other)`.

That's a classic caveat, see https://www.artima.com/pins1ed/object-equality.html -> pitfall 1.

- [x] Interfaces can't define `equals` method... hence the construct as in e.g. `com.virtuslab.gitmachete.backend.api.IBranchReference#defaultEquals` should be used.

- [x] Within this task, also add an ArchUnit check to forbid defining an `equals` method with wrong params and/or return type.

**Comment by mkondratek** [comment]
wow, it's a nice bug 😮
