### ISSUE TITLE
Trigger the reparsing of the machete file once the branch is created

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/git-machete-intellij-plugin#1281]
A follow-up after completing https://github.com/VirtusLab/git-machete-intellij-plugin/issues/429

Solution from https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1243 has one downside - after a new branch is created, the _reparsing_ of the machete file is not invoked. And because of that the `Can't find local branch...` error stays.

Reparsing should cause the `Can't find local branch...` error annotation to disappear.

**Comment by PawelLipski** [comment]
Taking over... probably restoring a call to `com.virtuslab.gitmachete.frontend.file.MacheteFileViewProviderFactory.MacheteFileViewProvider#subscribeToGitRepositoryChanges` (see https://github.com/VirtusLab/git-machete-intellij-plugin/issues/679) will be the fix

**Comment by PawelLipski** [comment]
Actually, let's first sort out #1288, as `com.virtuslab.gitmachete.frontend.file.MacheteFileViewProviderFactory.MacheteFileViewProvider#subscribeToGitRepositoryChanges` contains an offending `Disposer.register(project, messageBusConnection)` call
