### ISSUE TITLE
Move from `PropertiesComponent` to some alternative storage

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#1285]
## Why? 
`com.intellij.ide.util.PropertiesComponent` gives application-level storage. That means the settings like "don't show it again" for **merge warn dialog** and **reset to remote info dialog** are set for ALL projects. That behavior **was not** and **is not** intended by us. 

Moreover, `PropertiesComponent` uses `other.xml` file under the hood while the [docs](https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#implementing-the-persistentstatecomponent-interface) say:
> For application-level storage, it is strongly recommended to use a custom file, using of **other.xml** is deprecated.

Project-dependent storage seems to be critical for #832.

##  Solution 

Implement our own project-dependent storage (should not be very hard). We ve got docs:
https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#implementing-the-persistentstatecomponent-interface

...or find some existing intellij component that would allow us to store project-level settings.

**Comment by mkondratek** [comment]
Implementing our own storage can be useful for https://github.com/VirtusLab/git-machete-intellij-plugin/issues/270 too!

**Comment by mkondratek** [comment]
It turned out that we can use `PropertiesComponent.getInstance(project)` (note `project` argument). Let's postpone this one then.

**Comment by PawelLipski** [comment]
Actually... do we even need to keep this issue open? Is the `PropertiesComponent.getInstance(project)` solution deficient/deprecated in any way? 🤔

**Comment by mkondratek** [comment]
hm, okay then
