### ISSUE TITLE
Checker stub files (`config/checker/`) should be considered an input to Gradle JavaCompile tasks

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1300]
So that when stubs change, the inputs to compilation are considered changed.

**Comment by PawelLipski** [comment]
See https://github.com/kelloggm/checkerframework-gradle-plugin/issues/135 (no response in 2 years ☹️)

**Comment by PawelLipski** [comment]
There's no other support for stubs in that plugin... the only mention of stubs is just in https://github.com/kelloggm/checkerframework-gradle-plugin#providing-checker-specific-options-to-the-compiler

**Comment by PawelLipski** [comment]
There's no other support for stubs in that plugin... the only mention of stubs is just in https://github.com/kelloggm/checkerframework-gradle-plugin#providing-checker-specific-options-to-the-compiler

**Comment by PawelLipski** [comment]
There's no other support for stubs in that plugin... the only mention of stubs is just in https://github.com/kelloggm/checkerframework-gradle-plugin#providing-checker-specific-options-to-the-compiler

**Comment by mkondratek** [comment]
TBH I do not think we can even hope kelloggm/checkerframework-gradle-plugin:135 will be resolved.
Only a workaround could help.
On the other hand, the stubs do not change very often and even when they do - in most cases the code changes too so things are recompiled, right? Probably we not only must but even can live with it.

**Comment by PawelLipski** [comment]
Yeah, we've lived with that for a long time already... still, would be a nice (and rather simple) improvement

**Comment by PawelLipski** [comment]
Re-assigning to @LukaszKontowski... hope that you @MaciejG604 haven't started yet (probably not, given the non-trivality of #1303 😅)
