### ISSUE TITLE
Unmanaged current branch notification is shown too... proactively

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1308]
![image](https://user-images.githubusercontent.com/3383210/198705077-007b9fb7-436d-4537-80ae-2d224e9bf67d.png)

Two problems on this screenshot:

1. notification doesn't expire once the branch is added (it's been added via `git machete github checkout-prs`, which adds the branch to branch layout almost instantly after checking out... maybe some delay in how long the current branch is checked out would be useful)
2. notification is shown twice for the same branch

**Comment by PawelLipski** [comment]
Yeah, I'm getting it all the time, not good ☹️ 
![image](https://user-images.githubusercontent.com/3383210/198842545-f1bf2ebd-42c7-4a88-931d-bed80237edc7.png)

**Comment by mkondratek** [comment]
That is interesting 🤔 

I have just tried two things:
- checkout a branch that is unmanaged from the Git Log 
- executing `git machete github checkout-prs <pr-no>` (from both the IDE terminal and the "external" terminal)

The notification appeared only once for the first case which is expected (in particular it has not been shown in the second case which is expected too).

Running the version from the current develop on macOS.
---

1. Are you guys both using Linux?
2. Can you please provide specific steps to reproduce the issue?

**Comment by PawelLipski** [comment]
1. Linux indeed... such behavior might unfortunately differ b/w systems (b/c the details of how IntelliJ is watching the filesystem might differ) ☹️
2. In non-IntelliJ terminal, run `git machete add lol/xd/foo/bar`. Open IntelliJ. Status reloads, but the notification shows up.
If it doesn't show up as easily as that on Mac... then indeed it might a Linux-specific stuff ☹️

**Comment by mkondratek** [comment]
ok, I can try it on ubuntu tomorrow (I ve got everything my friend - ubuntu, macOS, windows)

**Comment by mkondratek** [comment]
ok, I ve tested the case described in your anser (2) - I confirm, the unexpected behavior happens on both linux (ubuntu) and macOS.

However, I did not encounter that one while running the git machete command from intellij's terminal (on both systems). The issue remains anyway for non-IntelliJ terminal (on both systems). 

Lemme see what can be done about it.

If you have more of specific scenarios of incorrect behavior let me know. In particular you have mentioned a situation when two notification are shown at once - give me the scenario for that.
