### ISSUE TITLE
UI tests: `java.lang.AssertionError: expected:<15> but was:<16>`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1329]
See https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/7640/workflows/ec66e612-e7b5-4c86-802f-93ca34ca95a2/jobs/8059

![image](https://user-images.githubusercontent.com/3383210/202766491-774c27f3-ebdb-4ece-8234-19d0c1bcdda7.png)

**Comment by mkondratek** [comment]
is it https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1079?

**Comment by PawelLipski** [comment]
Ouch indeed... lemme reopen that one instead...
