### ISSUE TITLE
Integration with Tasks & Context

### ISSUE THREAD

**Issue by CLOVIS-AI** [VirtusLab/git-machete-intellij-plugin#1348]
[Tasks & contexts](https://www.jetbrains.com/help/idea/managing-tasks-and-context.html) are an IntelliJ feature that allows to pull issue / ticket information directly from an external provider (GitHub issues, JIRA…). It allows users to create a branch automatically from a ticket, to automatically switch branches and changelists when switching tickets, and to time how long you pass on each task.

When starting to work on a task with Tasks and Contexts, the user selects a task and provides some information. One of the options is to create a branch from another one (e.g. Create branch `123-fix-thing` from `origin/main`).

Machete is not aware of branches created this way. This makes Machete cumbersome to use, as it is necessary to add the branch to the machete file after creating it.

Since the 'Open task' dialog has the name of the created branch and the branch it is created from, which is the information needed by Machete, would it be possible to have Machete extract that information somehow and update the Machete file itself?

**Comment by mkondratek** [comment]
Out of curiosity, how did you learn about this plugin? 🤔

**Comment by mkondratek** [comment]
Note: 
We have got this issue (somewhat related): https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1173

But if I understand correctly your proposal looks like that:
1. A new local branch is created from ANYWHERE (git4idea - the usual IDE-integrated way, git CLI, Task & context, and N other)
2. Git Machete finds out that the new branch appeared and adds it automatically to the layout 

Am I right?

**Comment by mkondratek** [comment]
It sounds like our recent feature (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/832).

Interesting 🤔 the slide-in suggestion dialog showed to you, or didn't it?

**Comment by CLOVIS-AI** [comment]
> Out of curiosity, how did you learn about this plugin? 🤔

I searched for Git plugins and found it 😅 I use rebase quite a lot, and having it automatically figure out `--onto` etc is really convenient.

> 2. Git Machete finds out that the new branch appeared and adds it automatically to the layout

For now I would be satisfied if you could somehow hook into the ‘New task’ screen and create the branch from it, since it has the name of the created branch and its parent. I haven't written IDEA plugins though so I have no idea if that's even possible.

**Comment by CLOVIS-AI** [comment]
I did not notice the dialog, is it in the notifications panel? If so, I'll take a look next time

**Comment by mkondratek** [comment]
Yeah, the notification (it's a proper name). Good point

**Comment by mkondratek** [comment]
FYI:

I have created a branch - `some-new-branch` from the integrated terminal (via `git checkout -b some-new-branch`) from branch `develop`. The notification looks like that:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/19799111/203587481-9fdcf65e-5ceb-4700-8214-ea1401895beb.png">


Also, I ve changed this issue from bug to feature (assuming that the slide in suggestion notification works as expected, and Git Machete - [Tasks & contexts](https://www.jetbrains.com/help/idea/managing-tasks-and-context.html) integration is a new potential feature to be considered if needed).

**Comment by CLOVIS-AI** [comment]
> Interesting thinking the slide-in suggestion dialog showed to you, or didn't it?

I just tested it, it's pretty good!

> I ve changed this issue from bug to feature

When creating an issue, only the 'bug' template appears, did you mean to also have a 'feature' issue template?

**Comment by mkondratek** [comment]
Cool, so we can assume the slide in suggestion notification meets your requirements and we can close this one! 🚀 

And yeah, we have the issue (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/961) to add more issue templates 🤣 

---

We are very happy that you find our plugin useful! 🔧  Thank you again for contacting us this way 🥇 In the case you find some "other" bugs or you will come up with new ideas (probably of more general functionalities 😉 ) do not hesitate to contact us again 🔁

**Comment by CLOVIS-AI** [comment]
Well I would still prefer if Machete could get the information automatically, but I agree that the notification is almost perfect :)
