### ISSUE TITLE
On `master` build: `Execution failed for task ':printSignedPluginZipPath'`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1356]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/7776/workflows/ca7bd676-008d-41cf-9db0-76670533e63c/jobs/8200

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/3383210/204086674-7d75e371-9a9f-44c5-ab13-2c7bd250cce0.png">

As a workaround, we can suspend passing the plugin zip as artifact to GitHub release for a moment 🤔

**Comment by PawelLipski** [comment]
I've created the v3.2.1 release manually btw

**Comment by PawelLipski** [comment]
Okay, trivial to repro locally...

<img width="996" alt="image" src="https://user-images.githubusercontent.com/3383210/204087764-b8a3d857-7b64-4775-a578-02f98df6d0c9.png">

What's weird is that on CI, `buildPlugin` is executed before the release hmmm 🤔

**Comment by mkondratek** [comment]
You mean that it should have failed before, right? even before merge to master (riliz)

**Comment by PawelLipski** [comment]
Nope, I'd just expect `printSignedPluginZipPath` not to fail at all, given the circumstances... anyway, lemme provide a workaround as for now, #1357 1️⃣ 3️⃣ 5️⃣ 7️⃣
