### ISSUE TITLE
Is autodiscover still working in case of missing .git/machete?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1369]
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/3383210/205076711-dfa27774-e562-4527-8744-cecf474192e0.png">

I shouldn't be seeing anything like that... .git/machete should be automatically discovered.

I'm looking into https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1224/files#... the change that was merged isn't probably what was expected in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1224#discussion_r987971256 😅 

Marking as SEVERE as it impacts the first-minute UX for the new users.

**Comment by mkondratek** [comment]
Please, do provide a specific steps to reproduce. It's not obvious thing to figure it out.

I ve tried
1. Open a project (filter service from machete sandbox script)
2. Delete the machete file (before opening the git machete tab)
3. Open the git machete tab

The branch layout is automatically discovered

**Comment by PawelLipski** [comment]
Please then
1. Close the project
2. Delete machete file
3. Open git machete tab

What I observe under v3.2.1 is on the screenshot above :/

**Comment by mkondratek** [comment]
I cannot reproduce this one - it simply works as expected to me 😞 

I have tried 
- running new instance from the develop branch with `runIde`
- using the "normal" IDE with the newest released version of the plugin

and deleting the machete file before the instance start up and with the project opened 

It works as expected.

**Comment by PawelLipski** [comment]
Okay... I'll investigate on my machine if time allows... the schedules recently are _as tense as the tarp in a Polish commie truck_!

**Comment by PawelLipski** [comment]
Cannot reproduce on Mac!

![image](https://user-images.githubusercontent.com/3383210/211216549-13eb7c3c-08c7-4008-b3fa-2b27840e8996.png)

**Comment by PawelLipski** [comment]
Awww crap I see now 🤦🏻 git-machete CLI (just any command) writes empty contents to .git/machete. Normally it wouldn't be a problem, as you wouldn't run `git machete <anything>` on a repo that has no/empty .git/machete... except I've got `git machete file` invoked in my PS1 for certain reason 😅 this touched the file without writing anything there
