### ISSUE TITLE
There's no point in Traverse checking out branches for which there's nothing to do

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1400]
I.e. which one in sync with both parent and remote. Checking out takes time, and might trigger External System (e.g. Gradle) reload unnecessarily.

`git machete traverse` never checks out such no-op branches.

**Comment by PawelLipski** [comment]
Hmmm I've got an impression this has been discussed on PR #1352 already... lemme check...

**Comment by PawelLipski** [comment]
Yeah...

<img width="292" alt="image" src="https://user-images.githubusercontent.com/3383210/209442793-ea801a96-0b7c-4615-9c9d-62feada526dd.png">

**Comment by PawelLipski** [comment]
Probably a regression then 🤔

**Comment by mkondratek** [comment]
> Yeah...
> 
> <img alt="image" width="295" src="https://user-images.githubusercontent.com/3383210/209442803-1e91dcf3-0690-4df8-a97b-d4e4e5f41b38.png">

whoops. sorry 😶 my fault - I should have been more careful
