### ISSUE TITLE
Traverse actions should be disabled when a traversal from the given branch would be a no-op

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1403]
I.e. when the given branch and all following branches are in sync both to its remote (or there are no remotes at all) and parent.

I wouldn't hide the Traverse from current action from the toolbar as it might be confusing, rather just disable with a description.

**Comment by mkondratek** [comment]
I rather consider it as a feature - no need to think if the traverse is needed for some particular branch or some next branch. the other thing is that git machete CLI allows to start the traverse from a branch that needs no action

**Comment by PawelLipski** [comment]
Still, the work is already done, #1405 ;)
