### ISSUE TITLE
`DivergedFromRemoteDialog` can be simplifed to a `MessageDialogBuilder.yesNoCancel`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1426]
Radio buttons seem inconsistent and redundant. Let's just add a `Force Push` button instead.

**Comment by PawelLipski** [comment]
The existing dialog for reference:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3383210/211211068-e05aec18-2f71-4a04-8037-07884d794467.png">

**Comment by PawelLipski** [comment]
And dialog for rebase for comparison:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3383210/211211120-27df71b1-88d8-4c38-86cc-c806c1776e16.png">

**Comment by mkondratek** [comment]
oh. ofc 🤦 very good. simpler. consistent with the other dialogs. the radio-version of the dialog made sense with more options possible but now it's redundant
