### ISSUE TITLE
Get rid of `RuntimeBinding` in favor of IntelliJ non-light services

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1459]
https://plugins.jetbrains.com/docs/intellij/plugin-services.html#declaring-a-service

As started in #1458.

Ideally, `binding` module and dependency on `org.reflections` to be removed.

Also, remove the whitelist on `..impl..` packages in `com.virtuslab.archunit.ClassStructureTestSuite#all_classes_should_be_referenced`

Almost all usages of `RuntimeBinding` are located in `frontend` modules, with a single exception of `com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryCache#GitMacheteRepositoryCache` in `backend:impl`.
We'll probably need to add dependency on IntelliJ to `backend:impl`... which isn't ideal, but still better than having two parallel mechanisms of dependency injection (IntelliJ services and `RuntimeBinding`).

Also, `RuntimeBinding` shows suboptimal performance (see #1457).

TBD if all IntelliJ services should be changed to non-light (i.e. declared in plugin.xml and **not** annotated with `@Service`): probably **yes**, for the sake of consistency.

**Comment by mkondratek** [comment]
can we close it now?

**Comment by PawelLipski** [comment]
:yes:
