### ISSUE TITLE
Does `queueRepositoryUpdateAndModelRefresh` need to be called from so many places?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1465]
Can't we generally just rely on listening to changes to .git/machete and git repository? 🤔

**Comment by mkondratek** [comment]
I think we can remove the refresh action from the toolbar btw

**Comment by PawelLipski** [comment]
My hypothesis it that while `queueRepositoryUpdateAndModelRefresh(@UI Runnable doOnUIThreadWhenReady)` is strictly useful in many places (like `traverse`)... `queueRepositoryUpdateAndModelRefresh()` might be completely useless
