### ISSUE TITLE
Traverse Action in toolbar should start from first branch, not from current branch

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1479]
Suggested by @radeusgd.
Traversing the entire tree seems to be the typical use case.
If someone really wants to start from the current (or any given) branch, they can always use context menu action _Traverse from Here..._

**Comment by mkondratek** [comment]
Not a ➖ of this. We will not be consistent with CLI 😭

**Comment by PawelLipski** [comment]
Hmmm I don't think that's such a big deal TBH 🤔

**Comment by radeusgd** [comment]
Hot take: what if the CLI default could be changed to remain consistent? :sweat_smile: 

I'm wondering what are the common usecases, personally I have an alias that I always use that traverses from root, I've never had a situation to traverse from current branch. But ofc that's just my usage pattern and it's quite possible others may do it differently.

**Comment by PawelLipski** [comment]
> personally I have an alias that I always use that traverses from root,

As in, `git machete traverse --whole`? or sth else?

**Comment by radeusgd** [comment]
> > personally I have an alias that I always use that traverses from root,
> 
> As in, `git machete traverse --whole`? or sth else?

Mine is `git machete traverse -F -w` to be exact. I also like to fetch the latest remotes to see if there are any new merges to `develop`.

**Comment by PawelLipski** [comment]
> git machete traverse -F -w

This is, in turn, aliased to `git machete traverse -W` ;D and that's also the most common combination for me... sometimes even the ultimate `git machete traverse -Wy` which doesn't ask for confirmation

**Comment by PawelLipski** [comment]
> Hot take: what if the CLI default could be changed to remain consistent? 😅

Maybe I wouldn't risk changing the default now after a few years... but adding a git config key to change the default behavior (as with `git config machete.traverse.push`) sounds like an option ;)

**Comment by radeusgd** [comment]
> > Hot take: what if the CLI default could be changed to remain consistent? sweat_smile
> 
> Maybe I wouldn't risk changing the default now after a few years... but adding a git config key to change the default behavior (as with `git config machete.traverse.push`) sounds like an option ;)

Fair point!
