### ISSUE TITLE
 Combine `Git Machete Traverse - Force Push` into `GitPushDialog`

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#1517]
## Feature description

Kind of similar to Slide In dialog and Create new branch dialog. 

In the present state we see
<img width="489" alt="image" src="https://user-images.githubusercontent.com/19799111/216785867-d0a096c5-0147-499d-b9dc-f7bf0d2a57a4.png">
and then
<img width="828" alt="image" src="https://user-images.githubusercontent.com/19799111/216785875-a9a6027b-3141-468f-9afd-f0ee2e12820d.png">

Technically I see no problem with `Git Machete Traverse - Force Push` triggering the force push directly once the `Yes` button is creating - omitting `Push Commits to <repo>` dialog.

### Arguments for:
- traverse more smoooother 🚀 
- CLI does not show the commits - we will be more consistent 🐚 

### Arguments against:
- one cannot see the commits 🙈 

It is likely that there are some other actions in traverse that could be simplified like this.

**Comment by mkondratek** [comment]
@ radeusgd I summon you to ~fulfill your oath~ share your views!

**Comment by mkondratek** [comment]
@radeusgd I summon you to ~fulfill your oath~ share your views!

**Comment by PawelLipski** [comment]
> one cannot see the commits 🙈

One could also argue that we could refine the built-in Push Commits dialog with the paragraph taken from what's now Git Machete Traverse - Force Push 🤔 thus both having smooth traverse and still displaying the commits

**Comment by radeusgd** [comment]
> > one cannot see the commits 🙈
> 
> One could also argue that we could refine the built-in Push Commits dialog with the paragraph taken from what's now Git Machete Traverse - Force Push 🤔 thus both having smooth traverse and still displaying the commits

IMHO that sounds like the best option if it is possible.

I think having to click twice to push the commits is indeed a bit unnecessary, so it would be cool to streamline it, but not losing the commit preview (even if the CLI does not normally show it) would be very cool too!

**Comment by mkondratek** [comment]
ok then - I will try to refine the push dialog!

**Comment by mkondratek** [comment]
- [ ] TBD what other step information dialogs can be merged together into corresponding action dialogs

**Comment by mkondratek** [comment]
@radeusgd, it should be available soon!

**Comment by radeusgd** [comment]
> it should be available soon!

@mkondratek I just got it and it looks really cool! 🎉 

![image](https://user-images.githubusercontent.com/1436948/230467349-2f47b1cf-8f33-42a0-bbb3-272447c89d85.png)

**Comment by mkondratek** [comment]
❤️ 🚀 👍
