### ISSUE TITLE
Make git submodules with directory mapping searchable

### ISSUE THREAD

**Issue by ppasieka** [VirtusLab/git-machete-intellij-plugin#1527]
## Feature description
I have a solution with over 200 other repositories attached as submodules. Could you make the module selector searchable?

![image](https://user-images.githubusercontent.com/2170707/218089118-f60c4aa2-9731-46d7-9df3-bf1267b238ed.png)

**Comment by mkondratek** [comment]
Hello 👋  I thinks it's doable! I must admit we never paid much attention to this particular feature since we never had any serious use cases for it 😅 but for your request we will try to deliver it soon! 🚀

**Comment by mkondratek** [comment]
And... out of curiosity, how did you learn about this plugin? 🤔

**Comment by ppasieka** [comment]
I started to use it after watching [this](https://www.youtube.com/watch?v=MxGwryMOKKk). It is hard to say precisely how I stumbled upon that video (most likely after reading a blog from my morning-brew feed). I liked the idea behind easier branch management. I have used the plugin for over half a year (in Rider).

Regarding the 'missing search,' I would not notice it, but I'm in the process of consolidating our NuGet packages, and git submodules seem to be an approach to make the process less painful 😂

**Comment by mkondratek** [comment]
> I started to use it after watching [this](https://www.youtube.com/watch?v=MxGwryMOKKk). It is hard to say precisely how I stumbled upon that video (most likely after reading a blog from my morning-brew feed). I liked the idea behind easier branch management. I have used the plugin for over half a year (in Rider).
> 
> Regarding the 'missing search,' I would not notice it, but I'm in the process of consolidating our NuGet packages, and git submodules seem to be an approach to make the process less painful 😂

oh, ofc. we have asked you about it already 🤦‍♂️  thanks for the detailed response ! 😄 

The features you requested are on the way! 🚀

**Comment by mkondratek** [comment]
merged to develop. @PawelLipski, when can we release it? 🚀

**Comment by PawelLipski** [comment]
Actually, lemme draft a release PR...
