### ISSUE TITLE
Slide-out in traverse tries to delete the current branch but fails

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1577]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/3383210/220162347-67a766e5-4c51-4eb0-b84e-14d0fd7f9c4b.png">

**Comment by CLOVIS-AI** [comment]
Hi, this issue is marked for 3.6.1. I'm currently using 3.7.0 and still have this problem, is it expected or should I create a new issue?

**Comment by PawelLipski** [comment]
Whoops it shouldn't occur anymore... lemme check 🤔

**Comment by PawelLipski** [comment]
Hmmm I cannot really reproduce the issue... can you provide a screen recording? is the problem deterministic, or just happens occasionally?

**Comment by PawelLipski** [comment]
Whoops okay I see! that's a different issue indeed, lemme close this one and open a dedicated one...
