### ISSUE TITLE
Fork point incorrectly (?) deemed too recently in the history

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#159]
Should be (?):
![image](https://user-images.githubusercontent.com/3383210/78168499-545fed80-7450-11ea-8e0b-d638abdfd5be.png)

Is:
![image](https://user-images.githubusercontent.com/3383210/78168523-62157300-7450-11ea-9a3c-d3c7a89f4c37.png)

Plugin version: `0.0.46-SNAPSHOT+git.b6b6f15`

.git directory: 
[git.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/4416745/git.zip)

**Comment by PawelLipski** [comment]
@mkondratek let's verify if that got solved with the recent PRs

**Comment by micpiotrowski** [comment]
This difference between CLI and plugin seems to be caused by forkpoint overriding (`git machete fork-point --override-to` CLI command or similar) that is handled in CLI but not yet in IntelliJ plugin
