### ISSUE TITLE
Try changing from custom solution for dependency&Gradle updates to dependabot

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1698]
Let's see if it deals well with `gradle/libs.versions.toml`. Plus also if it can update Gradle itself.

We'll still need to keep our custom solution for updating IntelliJ versions.

**Comment by PawelLipski** [comment]
Wowowow, instantly after merging #1699:

<img width="1422" alt="image" src="https://github.com/VirtusLab/git-machete-intellij-plugin/assets/3383210/e0b08759-f766-4a72-afb9-5957fa1b36b1">

**Comment by mkondratek** [comment]
that was fast xd
