### ISSUE TITLE
Propose automatically detected branch layout for user when machete file is not present or when it's empty

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#176]
Extracted from issue #44 

- [x] We want to propose automatically detected (by `discover` functionality) branch layout rather than only show message for user.

@PawelLipski :

- [ ] Note that the backend API for discover can be pretty easily configurable wrt. number of branches that we want to include in the discovered layout - most likely this could as well be configurable from the frontend.

- [ ] Also, the usage instructions (see #418) need to be updated

**Comment by PawelLipski** [comment]
Note that the backend API for discover can be pretty easily configurable wrt. number of branches that we want to include in the discovered layout - most likely this could as well be configurable from the frontend.

**Comment by PawelLipski** [comment]
- [ ] Also, the usage instructions (see #418) need to be updated
