### ISSUE TITLE
Ability to avoid saving context for root branches

### ISSUE THREAD

**Issue by CLOVIS-AI** [VirtusLab/git-machete-intellij-plugin#1825]
## Context

Currently, each time we slide into a branch, IntelliJ saves the [current context](https://www.jetbrains.com/help/idea/managing-tasks-and-context.html#work-with-context). This includes the list of opened files, which directories are open, unsaved run configurations, created favorites, etc.

In my workflow, I usually have two types of branches: 
- shared branches (`main`, `dev-VERSION-NUMBER`…) in which I do not make changes,
- feature branches, in which I do make changes.

In Machete, the shared branches are always the roots:
```
main
    2-a-feature
dev-3.2
    97-fix-bugs
    64-foo
```

## Problem

The context saving feature is great for in-development branches. However, I often slide into a shared branch to look at things in particular, or to check the behavior of a specific thing. This creates a bunch of junk info (junk run configurations, junk opened files…). Because context is inherited when creating a new branch, all this junk stuff slowly gets saved into all contexts of the project and becomes impossible to delete (switching back to any branch creates it back).

As a solution, could it be possible to have a configuration option that, when enabled, removes the context saving feature specifically for root branches in the `machete` file? This way, these branches would always have a pristine context, whereas dev/in-progress branches can keep the current behavior of saving the current project state.

**Comment by PawelLipski** [comment]
Hey, long time no see 👋🏻 that's an interesting one 🤔 

I've just realized that the feature of _contexts_ from Tools > Tasks & Contexts menu is used for saving _workspaces_ when switching branches 😯 The _Restore workspace_ notification doesn't use the _context_ term, only _workspace_. But indeed the saved workspaces seem to show up in contexts.

But first, as a sanity check:

1. in Settings, under _Version Control > Confirmation_, do you have _Restore workspace_ turned on?
<img width="487" alt="image" src="https://github.com/VirtusLab/git-machete-intellij-plugin/assets/3383210/ff093c84-924d-4976-93fd-1a8a6cbf566f">

2. If so, then does the _Workspace ... has been restored_  show up for you every time you switch the branch?
<img width="399" alt="image" src="https://github.com/VirtusLab/git-machete-intellij-plugin/assets/3383210/c673edb9-b2e0-4736-a7dc-803af10c96ba">

3. In Settings, under _Tools > Tasks_, do you have _Save context on commit_ turned on?
<img width="295" alt="image" src="https://github.com/VirtusLab/git-machete-intellij-plugin/assets/3383210/f929c675-cd37-419a-bd8e-c168c25f22de">

**Comment by CLOVIS-AI** [comment]
> in Settings, under Version Control > Confirmation, do you have Restore workspace turned on?

Yes. This is how I discover this is a standard IntelliJ feature, I was convinced it was added by Machete :)

> does the Workspace ... has been restored show up for you every time you switch the branch?

It does not. However, there is a good chance it did in the past and I muted the notification. I'm not sure how to check this.

> In Settings, under Tools > Tasks, do you have Save context on commit turned on?

Yes.

**Comment by CLOVIS-AI** [comment]
I have a complicated relationship with the context saving features :sweat_smile: At times, they are extremely convenient, but they also will keep trash coming again and again into the workspace.

**Comment by PawelLipski** [comment]
Hmmm in principle... it think what would solve your problem would be to turn off `Save context on commit` option every time you switch to a root branch, right? as this seems to be the sole moment when the context is saved automatically 🤔 

This option is saved under `.idea/workspace.xml`, under `<project>` -> `<component name="TaskManager">` -> `<option name="saveContextOnCommit" value="..." />`. Maybe a simpler idea would be to add a git `post-checkout` hook that sets/clears this option in `.idea/workspace.xml`, depending on the branch being checked out? 🤔

**Comment by CLOVIS-AI** [comment]
That seems... hacky :sweat_smile: Also, I do not believe IntelliJ reloads the configuration by itself when they change on disk, unless you reopen the project? At least, it doesn't reload run configurations when you change branches.

**Comment by PawelLipski** [comment]
> Also, I do not believe IntelliJ reloads the configuration by itself when they change on disk,

Hmmm yeah, that's possible, and relaunching IDE would be an overkill 😅 

Actually... I'm afraid that even turning _Save context on commit_ on and off might not be enough to solve this problem. CMIIW but it seems that the context is just saved automatically for all branches anyway (and _Save context on commit_ seems to just create extra named contexts accessible via _Tools > Tasks & Contexts > Load context_). 

So, a solution would be provided by one of two things:
* context **not** being automatically inherited by a newly-created branch (TBD what should the context associated with the new branch be then) OR
* context **not** getting auto-saved for selected branches (and then the newly-created branch would inherit just the last state saved for its parent branch, whenever it might've been created)

I'm not sure if either behavior is even configurable in Git4Idea aka vcs-git plugin itself... you might want to ask that plugin develops instead 🤔

**Comment by CLOVIS-AI** [comment]
Thanks for the info, I'll think about it and submit a proposal to the IntelliJ team.

Since this isn't at all related to this project, I'll close this issue, have a great day!
