### ISSUE TITLE
Show most important errors in a more noticeable form

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#183]
The most important errors like failing when creating graph (by any reason) or error while rebasing, ect should be shown in more noticeable form than entry in log (but ofc. in this also should be printed out to log with more details). The error `MessageBox` may be the best option I think.

https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/misc_swing_components.html

**Comment by PawelLipski** [comment]
@micpiotrowski is this covered by #214 as well?

**Comment by micpiotrowski** [comment]
Actually I think it is
