### ISSUE TITLE
Add support for 2024.2 EAP

### ISSUE THREAD

**Issue by simadin** [VirtusLab/git-machete-intellij-plugin#1860]
This plugin is very useful. Thank you!
I started to use CLion EAP 2024.2 and the plugin doesn't support this new version.

**Comment by PawelLipski** [comment]
...okay it's not so easy yet 😅 JetBrains decided to revamp the [Gradle plugin](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) used to build IntelliJ plugins... and to built for 2024.2 EAP, one needs to use this new revamped version, which is currently in Beta 🫠 I'm blocked on https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1634, I'll keep you posted on the updates.

Still, in the meantime, lemme check if the existing plugin version (v4.2.1) can be forced to run under 2024.2 EAP, even though it's built against 2024.1 🤔

**Comment by PawelLipski** [comment]
Pls check the [artifacts from the build](https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/10096/workflows/1d64e732-1672-4951-9074-d5112b4587b7/jobs/10539/artifacts) &mdash; [git-machete-intellij-plugin-4.2.2-7-SNAPSHOT+git.ecd60bf.zip](https://output.circle-artifacts.com/output/job/1b53cb28-1c00-48d0-894b-dc8b52b3e915/artifacts/0/git-machete-intellij-plugin-4.2.2-7-SNAPSHOT+git.ecd60bf.zip).

Go to `Settings > Plugins` and then `Install plugin from disk`:

<img width="419" alt="image" src="https://github.com/VirtusLab/git-machete-intellij-plugin/assets/3383210/f4acf0bf-54c8-4f71-b373-51244e1e031a">

**Comment by PawelLipski** [comment]
Still, this hasn't been checked for binary compatibility with 2024.2 EAP, so expect occasional glitches/runtime errors. I'd appreciate if you report them (there should be a `Report` button once you open the error message in IntelliJ).

**Comment by simadin** [comment]
Thank you. I tried this unofficial build and it seems to work for now

**Comment by PawelLipski** [comment]
Almost there, I'll get it v5.0.0 released soon
