### ISSUE TITLE
Subrepository created during plugin (IDE) runtime does not appear on subrepos dropdown

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#197]
**Steps to reproduce:**
1. Run IDE with the plugin with a single git repository
2. Create second sub-repository

**Expected:** 
- Dropdown with both sub repositories appears

**Actual:**
- No dropdown

---
In the case of a multi-repository project existing at the start of the plugin runtime analogical situation takes place (new repository does not appear on the dropdown list).

**Comment by mkondratek** [comment]
Keeping sub repositories in lexicographical order and removing presently selected sub repository from the dropdown might be considered by the way.

**Comment by PawelLipski** [comment]
> removing presently selected sub repository
Hmm I'd rather not implement this feature, this might be confusing (dropdowns like that across desktop/mobile/web apps rarely if ever hide the currently selected element)

**Comment by PawelLipski** [comment]
Also the case (rather rare in practice) of **removing** a VCS root can/should be taken into the account, esp. removing the last remaining VCS root (`GitMachetePanel`'s c'tor makes an assumption that 1+ VCS root is present, this might get tricky on this corner case)
