### ISSUE TITLE
Dispatch git push (also in `--force-with-lease` version) to IntelliJ git plugin

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#20]
Also: handle setting remote tracking branch while doing the push (`--set-upstream` flag of `git push`)

**Comment by mkondratek** [comment]
About **--force-with-lease**:

![image](https://user-images.githubusercontent.com/19799111/81058060-f2225e80-8ecd-11ea-8ff5-e1b771d24794.png)

In general, ide push uses registry option. By default, it is ON.

**Comment by mkondratek** [comment]
> Also: handle setting remote tracking branch while doing the push (`--set-upstream` flag of `git push`)

I think (correct me if I am wrong, @PawelLipski ) that it is provided by `VcsPushDialog`. Once you open it (ctrl + shift + K) you can click and modify both remote and branch. 

![image](https://user-images.githubusercontent.com/19799111/81058355-960c0a00-8ece-11ea-8f1c-8fe00385dc77.png)

**Comment by PawelLipski** [comment]
> click and modify both remote and branch

It'd be still theoretically possible that IntelliJ does the push but doesn't set up the tracking info (stored in git config under `branch.X.remote` and `branch.X.merge`), pls make sure :/

**Comment by mkondratek** [comment]
A line from `git4idea.push.GitPushOperation#doPush`:
`boolean setUpstream = target.isNewBranchCreated() && !branchTrackingInfoIsSet(repository, sourceBranch);`

I hope this answers your question :upside_down_face:
