### ISSUE TITLE
Increase spacing between graph nodes

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#206]
Hmm I think the tree might have become a bit too cramped now...

![image](https://user-images.githubusercontent.com/3383210/79595854-e0744500-80df-11ea-98f9-3703e2da8bc8.png)

This might result in "fat finger errors" where users (esp. on their high-res Macs :apple:) will click other branch that they really meant :/

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/194#issuecomment-615365064_

**Comment by PawelLipski** [comment]
The list-commits-on mode looks pretty neat though:

![image](https://user-images.githubusercontent.com/3383210/80583426-78432e80-8a10-11ea-997e-dd72cfd4a28f.png)

So ideally the extra spacing should only be added in the list-commits-off mode.

**Comment by PawelLipski** [comment]
Seems that just it'll be resolved with https://github.com/VirtusLab/git-machete-intellij-plugin/issues/489 and possibly #509

**Comment by PawelLipski** [comment]
So adding extra spacing won't be really needed
