### ISSUE TITLE
Gray out the "Toggle list commits" button when there are only root branches in the selected repository

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#207]
It'll have no effect anyway, and its availability might be pretty confusing

**Comment by PawelLipski** [comment]
Whoever does that: might be also worth taking a look why the Refresh button is sometimes grayed out (it generally shouldn't; although I'm aware that it might be sth to my Intellij installation and thus not only reproducible elsewhere)

**Comment by mkondratek** [comment]
About **Refresh**

After the quick investigation, I think it is worth to have a look at the following classes:
- `DumbAware`
- `PossiblyDumbAware`
- `AnAction`

Making `RefreshGitMacheteStatusAction` implement `DumbAware` seems to be a solution.

**Comment by PawelLipski** [comment]
Okay, the `Refresh` graying out while indexing is resolved, just the `Toggle`/root branches part is still left
