### ISSUE TITLE
Implement (optional) sliding out of merged branches

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#22]

**Comment by mkondratek** [comment]
Backend implemented in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/36
And tested in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/94

I suppose we now only need to provide a fronted (some button to slide out the current branch/dropdown option for selected)

**Comment by PawelLipski** [comment]
Yes, it's likely only the frontend that's missing currently

**Comment by PawelLipski** [comment]
Closed by #202.
