### ISSUE TITLE
Provide pluginIcon_dark.svg as well

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#224]
As for now, the plugin logo looks poorly in dark theme:

![image](https://user-images.githubusercontent.com/3383210/80406593-99970400-88c4-11ea-94a9-a032a19b9676.png)

Most likely the lower half's color should be inverted.

See Gradle plugin logo for reference.

**Comment by mkondratek** [comment]
![image](https://user-images.githubusercontent.com/19799111/80420871-cacefe80-88db-11ea-889a-4a05cca24114.png)

@PawelLipski, @micpiotrowski   WDYT?

**Comment by mkondratek** [comment]
closed by #226
