### ISSUE TITLE
Allow displaying graph when branch defined in machete file is only remote branch (but not local)

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#241]
This can be annoying that we must check out every remote branch defined in `machete` file but not present locally to get rid of error `com.virtuslab.gitcore.api.GitCoreNoSuchBranchException: Local branch '<branch name>' does not exist in this repository` and then allow to display the branch relation graph.
Plugin should check also remote branches and when branch defined in `machete` file is one of remote branches but not present locally they should normally display the graph but gray out options like rebase for this branch (checkout should stay available).

**Comment by mkondratek** [comment]
We decided to drop this idea.

1. It would make things too complicated (for users). In particular sync to parent status refers to the status between local branches - in the case of the remote branch, none of the statuses is applicable; theoretically, a new status would be required.

2. Soon we will provide options (quick actions) within the machete file (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1232) - one will be able to easily checkout remote branch.
