### ISSUE TITLE
Upload plugin screenshot(s) to Marketplace

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#268]
Check if animated gifs are possible.

**Comment by PawelLipski** [comment]
Also, embed an animated gif in README

**Comment by PawelLipski** [comment]
For record: https://github.com/phw/peek can be used for capturing screencasts as animated gifs; on Fedora, use Flatpak and not `dnf` to install.

**Comment by mkondratek** [comment]
Can be reviewed here: https://plugins.jetbrains.com/plugin/14221-git-machete

Due to marketplace files upload issues, we must use a single good quality gif (instead of multiple smaller) and ss from `Help Action`.

**Comment by mkondratek** [comment]
piggybacking on #351
