### ISSUE TITLE
Add support for overriding fork points directly from the plugin

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#307]
Continuation of #172 

---
Allow overriding to:
- parent
- inferred

**Comment by mkondratek** [comment]
### Checkpoint:
The first idea was to add action within the inferred commit row.
- adding action next to inferred commit may lead to "overpopulation"  of the row
![image](https://user-images.githubusercontent.com/19799111/88542816-56f5dc80-d017-11ea-82a4-b745aa963c72.png)
  - we could reorganize inferred commit row (probably get rid of specific reflog info)
- one must toggle listing commits to override fork point
- we would like to provide the ability to override "any" commit (not only inferred one) - calling this action from inferred commit would be unintuitive

In the face of these factors, we decide to add the action as a branch context menu action.
We can then provide this action from inferred too.

**Comment by mkondratek** [comment]
## Override Frok Point Dialog 
![image](https://user-images.githubusercontent.com/19799111/88544653-03d15900-d01a-11ea-9876-7808fbcaeb5a.png)

**Comment by PawelLipski** [comment]
> adding action next to inferred commit may lead to "overpopulation" of the row

Again the risk of overpopulation, but it'd be nice if the action is suggested for the yellow edge-connected branches themselves as well :thinking:
