### ISSUE TITLE
Improve UX in case of non-existent branch in .git/machete

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#308]
1. VCS notifier should specify that **Git Machete** repository instantiation failed (currently just `Repository instantiation failed`); also "instantiation" isn't very fortunate in a user-facing message, it's too much about our internals
1. Graph table should contain a clear indication as to why nothing has been rendered (currently it's just `Nothing to show`)
1. Button to edit .git/machete should become more exposed
1. Toggle commits button shouldn't be available (and possible some other buttons as well)

**Comment by mkondratek** [comment]
What about showing branches even though they do not exist? Can we do that?
- from a UX perspective, we would indicate missing branch somehow; IMHO more intuitive flexible and smoother 
- that would require changes to backend (and frontend) logic to allow and reflect the state of git machete branch without a local branch
- we would forbid probably most of the actions for such a branch, but potentially add new like `Create Branch` (if checkout does not cover this case)

**Comment by PawelLipski** [comment]
Yeah, quite seems doable! although more effort will be required to handle a lot of corner cases that probably emerge
