### ISSUE TITLE
Provide own icons

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#326]
There's a problem with hijacking icons like that: they're subject to change b/w Intellij versions, and at some point they might be changed so that they still will be adequate for their original purpose, but no longer match our use case. Maybe instead copy the original icon to our project?... TBD how that works with the IntelliJ's Apache license.

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/319_

---

In the scope of this task:
- decide which icons are required
- create new ones 
- ~JB icons that are to be resused shall by baked into our codebase~ (#328)

**Comment by PawelLipski** [comment]
\*Provide own icons, or at least make sure the ones that we use are baked into our codebase

**Comment by mkondratek** [comment]
Comment on `MACHETE_FILE` icon used by `Open Machete File Action`:
> Btw while you're here: I'd maybe use some icon with a paper & pencil (and not just paper) to indicate it's about editing, not e.g. just viewing

~ https://github.com/VirtusLab/git-machete-intellij-plugin/pull/301#discussion_r437384730

**Comment by PawelLipski** [comment]
@mkondratek do you think we can close that now?

**Comment by mkondratek** [comment]
yup. I think that the current approach is good enough. We basically

- use icons offered by IntelliJ where applicable (e.g. push)
- use our own icons when no applicable icon can be found among IntelliJ icons (e.g. squash)
- update icons with their newer versions when the newer versions are available among IntelliJ icons

closing
