### ISSUE TITLE
Rearrange actions in left-side vertical toolbar

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#357]
There's now too many actions in the toolbar for each of them to have an individual button:

![image](https://user-images.githubusercontent.com/3383210/85440229-217c5000-b58e-11ea-999a-d6dca700f2b1.png)

- [x] Consider grouping the existing actions

- [x] Consider moving help action higher up (although maybe not necessary after the grouping is applied).

**Comment by PawelLipski** [comment]
Also, my feeling is that Push button should be closer to Rebase button (and not separated by Fetch & Pull buttons) for the convenience of traverse-like flows.

**Comment by mkondratek** [comment]
New order :trollface: :
![image](https://user-images.githubusercontent.com/19799111/86486763-783b1400-bd5c-11ea-9428-878adc7ab489.png)

piggybacking on #407
