### ISSUE TITLE
Try skipping the Non-Project Files Protection dialog when editing .git/machete

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#358]
It would be better if this dialog does not show up:

![image](https://user-images.githubusercontent.com/3383210/85515112-0bf23f00-b5fd-11ea-82a4-531e356b64aa.png)

But it's more of a UX issue, just not to confuse the user. Also, this dialog is only shown once at the very beginning for any given project anyway.

**Comment by mkondratek** [comment]
Can you provide the specific reproduction steps?

**Comment by PawelLipski** [comment]
Weird... now I can't reproduce that myself :thinking: even doing `runIde` on a clean project (i.e. with build/idea-sandbox/ removed) was not enough :frowning_face:

**Comment by PawelLipski** [comment]
If nobody comes this across in the next few weeks, then let's close this issue definitively.

**Comment by micpiotrowski** [comment]
It's likely to be true for older versions of IntelliJ (e.g. `2019.3` that we drop).
I also not come this, so close.

**Comment by micpiotrowski** [comment]
Oh no, it is just appear when I try to edit (not only open) machete file on fresh IntelliJ instance  :/

**Comment by mkondratek** [comment]
Yeah, confirming. It is still present. :confused: 

I would rather increase the severity of this issue. I know it's gonna appear rarely (probably once) but sadly at the very begging of the plugin usage. :crying_cat_face:

**Comment by PawelLipski** [comment]
Right, that's gonna be an unfortunate part of first-time UX :/

**Comment by mkondratek** [comment]
I was unable to reproduce that. 

IMHO it should not happen since we have the following line:
```
NonProjectFileWritingAccessProvider.allowWriting(Collections.singletonList(file)
```

Without it, the non-project files projection dialog actually appears

**Comment by PawelLipski** [comment]
Oh! I see the exact combination that's leads to the problem... that's not related to the new version of IntelliJ or anything. Lemme re-close this ticket and open a new one
