### ISSUE TITLE
Only complete unmanaged branches in the .git/machete editor

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#359]
So that branches that are already listed in .git/machete aren't suggested (related: #341).

**Comment by PawelLipski** [comment]
Also, a repeated branch isn't underlined with red squiggles:

![image](https://user-images.githubusercontent.com/3383210/162627820-767a18aa-76ff-4149-8af5-4a9b2078a0d2.png)

**Comment by LukaszKontowski** [comment]
> Also, a repeated branch isn't underlined with red squiggles:

will be done in a separate issue: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1195

**Comment by mkondratek** [comment]
I am not convinced of this idea. I can imagine a situation when I want to reorganize the branch layout and at first, I am "repeating" a branch name in the new, desired place, and then I remove the primary occurrence of it. Why? E.g. I do not want to forget the branch name that I want to move. In our project, it may not be the case as we have general freedom of choosing branch names, but I think there could be projects with branches `feature/2137`, `feature/2317`, `feature/2137-2`, etc. So once you remove the first entry I may easily mistype it in the new place.

I would appreciate an opinion from someone outside of this project (@radeusgd can you share your feeling about it if you have any?).

**Comment by PawelLipski** [comment]
☝🏻 huh makes sense indeed... let's put this issue on hold then. #1195 is, however, non-controversial, methinks

**Comment by radeusgd** [comment]
> I am not convinced of this idea. I can imagine a situation when I want to reorganize the branch layout and at first, I am "repeating" a branch name in the new, desired place, and then I remove the primary occurrence of it. Why? E.g. I do not want to forget the branch name that I want to move. In our project, it may not be the case as we have general freedom of choosing branch names, but I think there could be projects with branches `feature/2137`, `feature/2317`, `feature/2137-2`, etc. So once you remove the first entry I may easily mistype it in the new place.
> 
> I would appreciate an opinion from someone outside of this project (@radeusgd can you share your feeling about it if you have any?).

We do have non-trivial issue names (`wip/<username>/<issue-shortname>-<issue-id>` where `<issue-id>` is a pretty long de-facto-random number) so it may be hard to remember the suffix - but if autocomplete helps with that it shouldn't be an issue either.

If I'm editing the machete file I'd normally use Ctrl+Shift+<Up/Down arrow> to swap lines and then fix indentation. So I would never remove a branch anyway if I want to keep it - so from my subjective perspective it doesn't really matter too much. I kind of like the fact that not-completing helps avoid writing the same branch twice, but I'm not convinced it changes much really.

**Comment by mkondratek** [comment]
cool. Thanks a lot for the extensive answer

**Comment by PawelLipski** [comment]
Closing then!
