### ISSUE TITLE
Enable syntax-aware editing of .git/machete from IntelliJ

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#37]
~It's not obvious coz by default the entire .git/ is marked as ignored in Settings>Editor>File Types...~ => OK, this doesn't look much of a problem though

**Comment by PawelLipski** [comment]
This feature also has to include some basic completion... typing branch names from memory or copying them from somewhere else is an obvious no-go ;)

**Comment by mkondratek** [comment]
Code completion reference:
https://www.plugin-dev.com/intellij/custom-language/code-completion/

**Comment by PawelLipski** [comment]
Also addressed by @mkondratek on #301 and #272
