### ISSUE TITLE
Some exceptions are thrown when edit machete file

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#371]
From time to time when machete file is edited in IntelliJ exceptions are thrown. For the first glance it's not directly connected with our plugin but it's worth to investigate this.

**Comment by PawelLipski** [comment]
@micpiotrowski `wontfix`?

**Comment by PawelLipski** [comment]
Could not be reproduced. Likely fixed by some subsequent changes.
