### ISSUE TITLE
Show VCS notifier warning when nonexistent local branch defined in machete file is omit while machete repository is instantiating

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#375]
For now when machete repository is instantiating and branch defined in `machete` file does not exist then this branch is silently omitted. There should be some kind of notification for user (preferably by VCS notifier - as warning) that some branches was omitted and why.

**Comment by mkondratek** [comment]
_Slack discussion summary_

- Some notification/event logging is needed.
- The notification cannot cover any previously shown notification (actions like push/rebase call refresh).
- Baring in mind :arrow_up: some kind of `silent` notification to event log is an option.

**Comment by PawelLipski** [comment]
Related to/part of #308
