### ISSUE TITLE
Regenerate sample GIF before the release

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#408]
Possibly both the focus on multiple VCS roots and showing the Project Explorer are redundant, TBD

**Comment by mkondratek** [comment]
- I agree about VCS root selection.
- I thought the same about Project Explorer during the first recording. Ofc we could reorganize windows within IDE to present only the opened machete file and graph table. The thing that I was afraid of is that it can lead us to a weird and unnatural layout.
