### ISSUE TITLE
Add basic info for newcomers into README.md

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#410]
And possibly create DEVELOPMENT.md or sth like that (linked from README.md, itself linking to CONTRIBUTING.md) for what's currently `Development` secton in README.md.

This should include a basic info for the newcomers about what this software does + possibly a bunch of screenshots

**Comment by PawelLipski** [comment]
Also include the info what JetBrains products the plugin is compatible with (currently all but Android Studio, see #392)

**Comment by PawelLipski** [comment]
+ mention the Ctrl-Alt-Shift-M shortcut

**Comment by mkondratek** [comment]
I think that since the `Custom Pages` (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/402) support markdown we can just share some (or all) of the files mentioned above there.
