### ISSUE TITLE
Provide a draft of blogpost for JB to review

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#413]
https://github.com/mkondratek/git-machete-blog-post/pull/1/files

**Comment by PawelLipski** [comment]
@mkondratek pls consider adding a mention of discover functionality (although it first needs to be actually released :/)

**Comment by PawelLipski** [comment]
(Blocked on response from JB team)

**Comment by mkondratek** [comment]
@PawelLipski can we close it?

**Comment by PawelLipski** [comment]
:yes:
