### ISSUE TITLE
Help does not display correctly with Dracula theme

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#419]
![image](https://user-images.githubusercontent.com/19799111/86614336-23dda180-bfb3-11ea-8feb-6aa25a3141cd.png)

It looks like the colors used by the table are the ones for the light theme instead of the dark.

**Comment by PawelLipski** [comment]
Hmm weird but it works correctly for me... at least as of `0.6.0-1-SNAPSHOT+git.5a408a1`:

![image](https://user-images.githubusercontent.com/3383210/86631549-8ee8a180-bfce-11ea-96b6-f9af2269fe6f.png)

**Comment by PawelLipski** [comment]
Looks like the issue has been introduced between `5a408a1` (still okay) and `fd69e0f0` (no longer okay)

**Comment by mkondratek** [comment]
That is not true. :c I am still experiencing this issue on `5a408a1`. 

I set out on my way to ancient times when the help action was introduced (`21a487d18d3388d1b3f38a6e5dad04cb1fd1f59c`) - it never worked correctly (for me (?)).
