### ISSUE TITLE
Display only single reset/pull/push/slide-out button for the current branch, depending on its state

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#427]
A single button could change between reset/pull/push/slide-out/nothing, depending on the state of the branch.

TBD: this would break our rule that we don't hide actions from the toolbar, just disable them :thinking:

**Comment by PawelLipski** [comment]
EDIT: added slide-out which should be suggested for merged branches

**Comment by mkondratek** [comment]
Remove unused action implementations ~ https://github.com/VirtusLab/git-machete-intellij-plugin/pull/450#discussion_r462966214

**Comment by PawelLipski** [comment]
Also, README.md (expanded on #452) needs to be updated
