### ISSUE TITLE
Machete file - provide Alt + Enter option to create non-existing branch

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#429]
Scenario:
1. Open machete file with IDE
2. Add new branch layout entry (root?/non-root) - a branch name that does not exist within the repo
// Newly added entry gets red underlining thanks to our syntax highlight.
// The red bulb icon appears & the `Alt + Enter` option to resolve the "issue" is available.
3. Press `Alt + Enter` and select `Create new branch`
4. Red underlining disappears and the new branch is  created 

TBD whether:
 - `new branch dialog` is required
 - the new branch shall be checked out

**Comment by PawelLipski** [comment]
Tentatively assigning to v0.6.0, but will possibly be postponed until v0.7.0

**Comment by PawelLipski** [comment]
@micpiotrowski would be nice if this also allowed for checking out a local branch tracking a remote branch (although if not trivial, this can be extracted to another issue)

**Comment by LukaszKontowski** [comment]
@PawelLipski , @mkondratek - currently the `Can't find local branch <branch_name> in git repository` does not distinguish between:
1. a branch name that does not exist (both locally and on remote)
2. a branch name that exists on remote, but is not available locally

In my opinion:
- the "Press `Alt + Enter` and select `Create new branch`" fix should be suggested only for the first scenario. 
- And for the second scenario - we should have another suggestion - add local tracking of the existing branch from remote

What do you think?

**Comment by PawelLipski** [comment]
+1, exactly, this are two somewhat separate tasks. We can first have Alt-Enter context menu entry/action for (1.), and only then implement an entry/action for (2.)

**Comment by mkondratek** [comment]
yes, good point. I did not realized that they are different in the first place
