### ISSUE TITLE
Expose `getParent` from the `BranchLayoutEntry`

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#430]
Hmm consider exposing `getParent` from the `BranchLayoutEntry`... just as done for `GitMacheteNonRootBranch`, or on #415 for `MyBranchLayoutEntry`

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/407_

**Comment by PawelLipski** [comment]
Taking this one over myself...
