### ISSUE TITLE
Repository instantiation failed error after branch deletion

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#436]
![image](https://user-images.githubusercontent.com/19799111/87415678-ba225080-c5cd-11ea-9b70-6d6a5297f7b7.png)

### steps to reproduce:
**given**
branch layout with an entry and its local branch
**when**
delete the corresponding branch 
**then**
- expected TBD
- actual error popup

**Comment by PawelLipski** [comment]
TBD, but I think we should never block the UI with a alert like that in case a branch a missing

**Comment by mkondratek** [comment]
This is possibly a different issue but somewhat related.

Appears on `ba277eca62e16c84abb61335ed3a7cddfb006c53`.
**Sometimes** slide-out causes the very same error popup.
It looks like the `write` to branch layout file finishes **after** repository reinstantiation.

**Comment by mkondratek** [comment]
The case described above has been covered by #405.

I will verify other cases when the popup could appear

**Comment by mkondratek** [comment]
> This is possibly a different issue but somewhat related.
> 
> Appears on `ba277eca62e16c84abb61335ed3a7cddfb006c53`.
> **Sometimes** slide-out causes the very same error popup.
> It looks like the `write` to branch layout file finishes **after** repository reinstantiation.

This was caused by async execution of branch deletion & repository update. 
Fixed on #443
