### ISSUE TITLE
Add support for overriding fork points - listed and unlisted commits

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#449]
Issue #307 covers the following cases:
- overriding to parent
- overriding to inferred

***
## The scope of this task

Enhance the `Override Fork Point` Dialog with an option (aka radioButton) containing a combobox with a list of commits.
We should allow overriding fork point to one of the branch commits (listed) and of the older ones (not listed).

For UI see: https://jetbrains.org/intellij/sdk/docs/user_interface_components/kotlin_ui_dsl.html#combo-boxes

**Comment by mkondratek** [comment]
> now my use cases might be weird... but after using a snapshot build from this PR for a couple of hours on a different project, I actually needed to override fork point for a red-edge branch... so TBH including red branches won't hurt.
> 
> I don't remember a single case, though, when I needed to override it for a green edge, let alone gray edge... so probably these can be skipped.

~ @PawelLipski, https://github.com/VirtusLab/git-machete-intellij-plugin/pull/450#discussion_r461751775

**Comment by PawelLipski** [comment]
Whoops this should not have been closed by #450, reopening & unlinking

**Comment by mkondratek** [comment]
PR comments are less readable (sometimes they are collapsed together, sometimes they are resolved and hidden eventually) so I will point out some findings/decisions here.

1. Commits order:
    1. unique commits until parent in the same order as in git machete tree
    2. fork point
        - if fork point is present among the unique commits until parent then it remains in its place
        - if fork point is not present among the unique commits until parent then it is added BEFORE them 
    3. parent - the same rules as fork point (but applied later) 
2. A reference dialog (smth we have seen somewhere so we can follow UI patterns / remain consistent): 
    - Register New File Type Association dialog (https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1168#discussion_r997156094)

**Comment by PawelLipski** [comment]
Ad 1.iii.: shouldn't parent commit be the **first** in combobox? to mimic the order of commits in git machete status (top to down == oldest to newest)
