### ISSUE TITLE
Figure out the possible consequences of skipping `untilBuild` completely

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#460]
Skipping `untilBuild` would be useful since we won't need to make a release that just updates `untilBuild` every three-four months **f o r e v e r**...

But! what if we skip `untilBuild` completely, and then a new quarterly release comes out and breaks binary compatibility for us? :thinking: 
Will Marketplace allow the users for downloading a plugin that does NOT pass their binary compatibility checks?

**Comment by PawelLipski** [comment]
See https://youtrack.jetbrains.com/issue/IJSDK-888; possibly opening an issue against https://github.com/JetBrains/intellij-plugin-verifier is a good idea as well

**Comment by PawelLipski** [comment]
Ok, received an answer on YouTrack:

```
Currently, plugin repository does not take information from compatibility checks for marking/making unavailable incompatible plugins to users. Please watch IDEA-195802 for progress on that feature.

Effectively, omitting until-build in your plugin puts risks in developers hands as newer IDE versions could become incompatible. Existing incompatible releases can be marked later with "proper" until-build manually on plugin repository if required.
```

**Comment by PawelLipski** [comment]
What this means for us is that we **cannot** skip `untilBuild` and yes, we do need to make a separate release with every following IDEA release.

The most reasonable approach to avoid a "downtime" (when the users already have a new IDE version `X` but our plugin doesn't work since it hasn't been released for `X` yet, only `X - 1`) is to extend `untilBuild` to `X.*` when a `X EAP` or `X RC` is ready. Once `X` is released, we should verify ASAP that our plugin is also compatible with `X`. There's generally rather little chance that a plugin compatible with `X EAP` (let alone with `X RC`) and does NOT use any EAP-specific features (i.e. is also compatible with `X - 1`) will NOT be compatible with `X` itself.

**Comment by PawelLipski** [comment]
@micpiotrowski pls add the above conclusions to the release docs on #452

Also, see https://youtrack.jetbrains.com/issue/IJSDK-701

**Comment by micpiotrowski** [comment]
Already done

**Comment by PawelLipski** [comment]
Closing the issue: the conclusion is **NO, we can't skip `untilBuild` at all**; the only action was to add the adequate docs

**Comment by PawelLipski** [comment]
Note: the answer might change in the future, but this hinges on development from JetBrains' side
