### ISSUE TITLE
Shorten context menu action text

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#461]
Git Log uses very simple short names for actions:
![image](https://user-images.githubusercontent.com/19799111/88925789-4fcc0a00-d275-11ea-8606-3e378f1901a5.png)

Let's try to keep our context menu action texts as short as possible.
- avoid `selected`, `current`, `branch` (eg. `Checkout Branch` -> `Checkout`)
- TBD: fast forward etc
- update gifs/READMEs/docs/intrusctions/pics

**Comment by PawelLipski** [comment]
Also, since https://github.com/VirtusLab/git-machete-intellij-plugin/pull/452/files references the action names in a few places (both in text and on gifs), remember to update docs/ and README.md once we decide on the final wording
