### ISSUE TITLE
Toolbar actions may be confusing now that rows are selectable

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#489]
Consider the following:

![image](https://user-images.githubusercontent.com/3383210/89317815-331d4100-d67e-11ea-83a3-eed8fcdfc25e.png)

The current branch is `bugfix/ci-no-cuda` which is currently in sync with remote, hence push button is disabled; the selected branch is `develop` which is in the need of a push, though. This is bound to be confusing to the users, even I myself thought for a moment its's a bug :trollface: 

Possible solutions:
1. toolbar actions refer to the selected branch, or in the absence of such, to the current branch OR
1. at least the descriptions/alt-text of actions should state the current branch name

Closely related to #461

**Comment by PawelLipski** [comment]
(FYI @micpiotrowski since #461 is assigned to you)

**Comment by mkondratek** [comment]
I am afraid that still, it is a case but we should remember about the description below

![image](https://user-images.githubusercontent.com/19799111/89526122-9080d180-d7e7-11ea-8470-6902f3c94f96.png)

**Comment by PawelLipski** [comment]
As discussed with @xgarrett, we shouldn't rely on the users noticing the description at the very bottom :/

**Comment by mkondratek** [comment]
A possible solution:
- let's add a `CURRENT BRANCH` prefix to the branch (like `REBASING` / `CHERRY-PICKING`)

**Comment by micpiotrowski** [comment]
Another idea would be making selection visible only when a context menu is shown.
