### ISSUE TITLE
Add discover frontend option to configure number of discovered branches

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#493]
From issue #176 by @PawelLipski:

> Note that the backend API for discover can be pretty easily configurable wrt. number of branches that we want to include in the discovered layout - most likely this could as well be configurable from the frontend.

**Comment by mkondratek** [comment]
TBD handling of this

we can:
- precede with some `Discover Setup Dialog` with checkboxes, number fields etc
- add all of these settings to the settings tab

**Comment by mkondratek** [comment]
We decided to drop this idea.

1. The number of branches does not correspond to any practical use case. The question is what branches we want in the graph table; not how many of them.
2. In most cases it is configured once for a long time.
