### ISSUE TITLE
Resolve `relation` vs `status` inconsistency b/w sync to parent and remote

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#499]
Rename:
`SyncToRemoteStatus` => `RelationToRemote`
`Relation` (inner enum of `SyncToRemoteStatus`) => `SyncToRemoteStatus` (can maybe even made a top-level enum, rather than an inner enum)

This way both `SyncToParentStatus` and `SyncToRemoteStatus` are enums, which is more consistent.

Also, remember to update the other derived identifiers, like the field `relation`, method params etc.

**Comment by PawelLipski** [comment]
Ok @IzabelaLindner my suggestion for renaming:
`SyncToRemoteStatus` => `RelationToRemote`
`Relation` (inner enum of `SyncToRemoteStatus`) => `SyncToRemoteStatus`

This way both `SyncToParentStatus` and `SyncToRemoteStatus` are enums, which is more consistent.

Also, remember to update the other derived identifiers, like the field `relation`, method params etc.
