### ISSUE TITLE
Investigate weak performance for larger graphs

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#50]
As discussed today, apparently sth in this method leads to weak performance for larger graphs... ofc this can be investigated & resolved after this PR is merged

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/28_

**Comment by PawelLipski** [comment]
Meh, lemme open a new issue instead
