### ISSUE TITLE
Completion in machete file editor is unnecessarily blocked on project indexing

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#506]
Just do `runIde` and open a project that hasn't been previously indexed by the sandboxed IDE (possibly clearing build/idea-sandbox/ might be needed to remove the existing indices). While the project is indexing, press Ctrl+Space somewhere in its machete file... this will (always? sometimes?) say that the project is indexing and no suggestions are available.

This obviously should not be the case for us... a research is needed if its possible to even a provide a completion in IDEA that doesn't block on indexing (maybe that's the completion's inherent nature?).

**Comment by micpiotrowski** [comment]
Yeah, in general during a project indexing `IDE’s features are restricted to the ones that don’t require index: basic text editing, version control etc. This restriction is managed by 'DumbService'`
But fortunately, it's enough to our class implements `DumbAware` interface (this is interface without any methods) to `DumbService` allow processing of this class.
