### ISSUE TITLE
Discover Branch Layout discovers all as roots

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#516]
### Bug description
as within the title

### Steps to reproduce
1. discover branch layout with the provided `.git`

### Expected behavior
discovered branch layout like within git machete cli (?)

### Current behavior
all branches are roots

### Screenshots
![image](https://user-images.githubusercontent.com/19799111/90174281-049e1500-dda6-11ea-8cb5-bab2485581a1.png)

![image](https://user-images.githubusercontent.com/19799111/90174317-12ec3100-dda6-11ea-9c7d-648552212293.png)

### Additional context
`.git` file:
https://drive.google.com/file/d/1rMnE2fp2oAIeU8iNS61fLU2XBaPzA0mJ/view?usp=sharing

**Comment by PawelLipski** [comment]
Whoops... I see the issue, the plugin (as opposed to CLI) doesn't really take advantage of the **reflogs of remote branches**. In this specific case, it completely did not care about reflog of `origin/master` and hence didn't infer `master` as the parent for any branch.
