### ISSUE TITLE
Reset to remote action possibly doesn't need to checkout the branch in question

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#523]
Possibly that just a matter of using a similar approach as for `BaseFastForwardParentToMatchBranchAction` or `BasePullBranchFastForwardOnlyAction` (`git fetch` for updating non-current branch, `git merge`/`git pull`/`git reset` for updating the current branch)

**Comment by mkondratek** [comment]
That would be a very nice improvement. For me, one of the strongest points of Git Machete is the ability to manage branches without checking them out (as by the actions mentioned above). :rocket:
