### ISSUE TITLE
Sort out sample workflow GIF (share between this repo and KSIUJ/pz.ksi?)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#542]
- [x] The current sample workflow GIF is too detailed (starts with editing machete file which is not so relevant & a bit boring), let's change that
- [x] We could simply use the one that's use for https://pz.ksi.ii.uj.edu.pl/companies/virtuslab-git-repository-organizer-rebase-automation-tool-as-intellij-idea-plugin.html, although maybe re-recorded to reflect new context menu entry names 
- [x] My bad, I moved the pz_sample_workflow.gif file to pz.ksi.ii.uj.edu.pl/ folder and now pz.ksi.ii.uj.edu.pl doesn't have any GIF :man_facepalming: sooo... now that a single GIF will be used for both repos, maybe let's just remove pz_sample_workflow.gif completely + link this repo's sample_workflow.gif from KSIUJ/pz.ksi's README (or copy the GIF directly to KSIUJ/pz.ksi to remove dependency on this repo)

**Comment by mkondratek** [comment]
PR to pz repo created: https://github.com/KSIUJ/pz.ksi/pull/6
