### ISSUE TITLE
`Discover the repository branch layout` link doesn't seem to work at all

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#545]
Nothing happens when the link is clicked (not only during project indexing) :/

`Discover Branch Layout` action is available under Ctrl+Shift+A and can be launched, however.

~It would be nice to find the other places that can be affected by indexing (i.e. are not `DumbAware` although they should be), or even maybe provide a more systematic way to detect them.~ EDIT: likely not relevant for this issue

UPDATE: as agreed, we're skipping the discover dialog completely:
- [x] discovery should happen automatically if .git/machete is missing or empty
- [x] UI tests should cover both regular discover & autodiscover
- [x] links should be forbidden across the project (via Checkstyle or FenumChecker)
- [x] README and docs/plugins.jetbrains.com/general_usage_instructions.html should be updated adequately

**Comment by mkondratek** [comment]
Tested on `0.7.0` (released)

Works for both missing- and empty- machete file.

**Comment by mkondratek** [comment]
_Slack discussion update_

A possible solution is to use a button instead of the link. 
We gain the ability to test the feature in particular then.

**Comment by micpiotrowski** [comment]
I also confirm. Link is not treated as link but rather ordinary, blue text.
