### ISSUE TITLE
Replace @PawelLipski's GitHub token in CircleCI with a GH service account token

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#546]
The current `GITHUB_TOKEN` in CI allows for full access to all public repos that I have the access to... Not Good :tm:

- [x] find out if GH allows for service (non-human/machine-use-only) accounts
- [x] create a machine account X if possible; if not, just create a regular account X
- [x] grant X access to git-machete-intellij-plugin repo (just enough for `hub` to read repo + create a release/PR - see .circleci/config.yml)
- [x] share the credentials of X to LastPass with @PawelLipski (and @micpiotrowski if he's got LastPass)
- [x] generate token for the account (as narrow scope as possible, most likely just `public_repo`)
- [x] replace `GITHUB_TOKEN` in CI's secrets with the new token
- [x] ensure that @PawelLipski revoked his token when no longer necessary :)
- [ ] change phone number for 2FA to @PawelLipski's
- [x] comment implicit `GITHUB_TOKEN` usage

**Comment by mkondratek** [comment]
### What (who) the "machine user" is...
https://github.community/t/confused-by-machine-user-docs/14513
It is a regular account (with email and password)

**Comment by mkondratek** [comment]
### Update
LastPass (team) account created. 
@PawelLipski, @micpiotrowski I added you to the team (I assume you should receive an email XD).
Sadly, the shared folder does not work. I cannot see any of its content. Hence I just shared the site for GitHub account of #git-machete-intellij-plugin-bot.

**Comment by mkondratek** [comment]
@PawelLipski please take the remaining step from here
