### ISSUE TITLE
Investigate if there's an easy way in the push dialog to show a list of possible target remotes

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#549]
Based on feedback of @MichalBednarz: _Is there any way to change the remote that changes are pushed to?_

He's sometimes pushing to `origin` and sometimes to some other remote (like his own fork of the original repo).

This task does **not** cover any implementation, just assessing what's possible and what's the required workload.
We'll decide separately if/when this is going to be implemented - can end up in v0.7.1, but can as well be postponed to v0.8.0 or even indefinitely (if e.g. there's no reasonable support for this feature in git4idea as for now).

**Comment by mkondratek** [comment]
Isn't it implemented already? 

![img](https://media.giphy.com/media/ib9kfZuI4r5wBASCfI/giphy.gif)

**Comment by PawelLipski** [comment]
Whoops right... @mkondratek  if you could just add just a short note to README like `Note that the standard allows for selecting the target remote to push to` or sth

**Comment by mkondratek** [comment]
piggybacking then on #555
