### ISSUE TITLE
Consider allowing Push action for branches in "Behind" state

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#559]
This may be useful while splitting branches (PRs) into two (or more) by commits.

**Comment by PawelLipski** [comment]
@mkondratek hmm for clarity, could you provide a specific scenario? :thinking:

**Comment by mkondratek** [comment]
## scenario:
1. Having a branch **feat_1** with two commits:
- commit A (older) 
- commit B (newer)
2. For some reason (separability of changes' topics, amount of changes, risk of exponential review comment overload :Xd:, whatever) a decision to split the commits between two separate branches has been made
3. The user checkouts a new branch **feat_2** from **feat_1** (both are point to the **commit B**)
4. The user resets branch **feat_1** `--hard HEAD~1` in our case (or perform rebase with a drop)
5. **feat_1** is `behind` and needs to be pushed

Eventually, **feat_1** is to contain **commit A**,  and **feat_2** is to contain **commit B**.

Is it clear now?

**Comment by PawelLipski** [comment]
Hmm TBH it's a rather rare case... I don't remember when I needed to do sth like that myself (although it isn't completely foreign to me, either) :/

Note that this will most likely require an action from command line anyway (`git reset` as you mentioned), so the user will most likely already be prepared to issue yet another command.
I don't think we should support every possible scenario; being too inclusive might be confusing for the users and runs against the purpose of left-side bar - to suggest the most viable action for the current branch's state.

**Comment by mkondratek** [comment]
okay then, I think we can close this one
