### ISSUE TITLE
Handle no local branch case by auto discover

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#562]
Another case is when there is no local branch withing the repo. Shouldn't refresh show some notification (`"No local branches within the repo"` or smth)? Presently nothing happens

_Originally posted by @mkondratek in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/550#issuecomment-685762147_

**Comment by mkondratek** [comment]
One can check out some revision by commit hash and delete all local branches (master in particular). Should we handle this case?

**Comment by PawelLipski** [comment]
Closely related to #706

**Comment by mkondratek** [comment]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/19799111/174391363-095278ad-1979-4f5e-872e-34f63847e770.png">

This is what we have now after sliding out (and deleting!) all branches - I think it's ok. We probably could split it into three lines b/c the msg is a bit too long.

**Comment by mkondratek** [comment]
The question remains what to do when we are sliding out all branches while keeping the local branches (no delete). 
The "problem" is that after sliding out the last branch the autodiscover auto discovers whole tree.

![image](https://user-images.githubusercontent.com/19799111/174391772-df08a1fc-b438-4bb9-b37b-856f38837039.png)

IMHO it's not a problem - that is simply expected reasonable behavior. WDYT @PawelLipski, @azdrojowa123 ?

**Comment by PawelLipski** [comment]
> The "problem" is that after sliding out the last branch the autodiscover auto discovers whole tree.

This is in fact pretty such an exotic corner case... in fact I wouldn't bother now that I take another look at this issue 😅 

As long as the handling of the (somewhat expected, at the beginning of a repo's lifetime) no-local-branch case is correct... we're good to go
