### ISSUE TITLE
Notification should NOT mention `Fetch` when action like reset or fast-forwarding parent is complete

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#563]
We implement these actions as `git fetch . <refspec>` under the hood when the modified branch is NOT the current branch... but exposing this detail to the user might be confusing. Esp. that most people (including myself before @mkondratek made me realize this) don't know that `git fetch` is actually so versatile that it can implement operations like `merge --ff-only` or `reset` on the current repository.

Note: this applies to both success&failure message.

**Comment by mkondratek** [comment]
Good point, this is definitely t0o specific, probably even for `Event Log` itself.

![image](https://user-images.githubusercontent.com/19799111/92133738-0426f600-ee09-11ea-9e36-2d786d87bffb.png)

Note that the detailed message (command actually) is visible from the `Console` tab anyway.

![image](https://user-images.githubusercontent.com/19799111/92134130-70a1f500-ee09-11ea-92c4-f632925c60a2.png)

**Comment by mkondratek** [comment]
Somewhat related...

![image](https://user-images.githubusercontent.com/19799111/92917164-84afad00-f42e-11ea-9a89-5f111e5fa94a.png)
