### ISSUE TITLE
Add optional ability to move the tip of a branch with no commits on slide in

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#566]
# Scenario

1. Having a branch `foobar` with at least one commit under `master`
2. Create a new branch `lolxd` with no commits under `master`
3. **Slide In** `lolxd` under `foobar`

## Actual:
`lolxd`  pointing to the same as `master`
## Expected(?):
`lolxd` pointing to the same as `foobar`

---

This functionality may appear as inconsistency as **Slide In** does not modify the repository itself.
On the other hand, we (OPTIONALLY!) do modify the repo on **Slide Out** (delete on slide out).
Hence we could keep the present behavior as a default one but add the optional feature.

TBD if the option should be defined by 
- git config 
- or IDE registry key,
- or IDE settings (depends on #270).

**Comment by mkondratek** [comment]
We decided to drop this idea.

1. Presently Slide In in such a situation warns and allows to perform a reset to a parent.
2. One can quickly work it out with the machete file edit.

**Comment by PawelLipski** [comment]
> Presently Slide In

I think you mean **Rebase**, right?

**Comment by mkondratek** [comment]
yes
