### ISSUE TITLE
Machete file opened in the editor is NOT updated when status is refreshed

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#568]
It is updated on disk, but not in the editor tab.

Unfortunately, this might be a limitation of IntelliJ PSI/VFS... let's research if the UX can be improved here

**Comment by PawelLipski** [comment]
I hope it's just a matter of `VfsUtil.markDirtyAndRefresh(...)` invocation as in `GitCommandUpdatingCurrentBranchBackgroundable#handleResult` :pray:

**Comment by mkondratek** [comment]
I ve just tried it. 

having machete file opened and sliding a branch out it still remains :c 
disappears after closing and reopening the file

**Comment by PawelLipski** [comment]
> I ve just tried it.

@mkondratek you mean you wired up `VfsUtil.markDirtyAndRefresh`?

**Comment by mkondratek** [comment]
> > I ve just tried it.
> 
> @mkondratek you mean you wired up `VfsUtil.markDirtyAndRefresh`?

Whoops, I now see I did it wrongly. NVM, ignore my comment
