### ISSUE TITLE
It's unclear whether `Slide out` deletes a branch or not

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#571]
There's theoretically a dedicated git config... but that's rather an obscure setting, this should more obvious from the UI itself.
Possibly two actions should be visible in the context menu/toolbar instead of just one: `Delete` and `Slide out without deleting`?

Inspired by @xgarrett :przemex:

**Comment by mkondratek** [comment]
It's a trap.

Once we provide explicit `Delete` for a branch what would stop us from adding other `git4idea` branch actions?

![image](https://user-images.githubusercontent.com/19799111/92713872-c58ac180-f35b-11ea-80c4-3ef1ce1d4712.png)

(`Rename...` looks interesting... :thinking: :laughing:)

---

What about adding a "don't show it again" (aka `DoNotAskOption`) dialog informing that the deletion is possible?

**Comment by PawelLipski** [comment]
Okay! you're right, we should avoid https://en.wikipedia.org/wiki/Inner-platform_effect

So maybe indeed, as in Reset to Remote action - just display a notification about NOT deleting by default + a info about `git config`?

**Comment by mkondratek** [comment]
Wow this is interesting! :nerd_face: 

This sounds good. So... 
- by default (the config **off**) notify that **the branch has been slid out has not deleted**
- if the config is **on** notify about both slide out and deletion
- have the info about the config in the docs (done already)

right?

**Comment by PawelLipski** [comment]
@mkondratek Yeah, let's do it this way, possibly can be improved later on this PR/in the future
