### ISSUE TITLE
README is too overwhelming

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#572]
As suggested by @mkondratek:

_I would reduce the README size and instead keep detailed feature docs in a separate .md file (a link could say "git master already? see the full feature list"). README itself should just show 2-3 simple scenarios..._

... which can include:
* stacked PRs ("sequential" setup)
* multiple PRs directly to develop ("parallel" setup)
* reviewing other ppl's branches (possibly in mixed parallel-sequential setup)

Inspired by @jakubbania :)

**Comment by mkondratek** [comment]
@PawelLipski what do you exactly mean by `reviewing other ppl's branches (possibly in mixed parallel-sequential setup)`?

**Comment by PawelLipski** [comment]
@mkondratek just the stuff I'm doing now:

![image](https://user-images.githubusercontent.com/3383210/93105153-0150be80-f6af-11ea-8b9c-64112ba93e33.png)

(maybe the sample should be a bit simpler)

**Comment by mkondratek** [comment]
Okay, but I do not get the scenario behind.

0. all in sync
1. checkout remote branch? how? from `(D)vcsStatusWidget`? From terminal? from Git Log? Pull dialog? 
...

or simply...

0. all in sync
1. fetch (someone's branch gets out of sync to remote)
2. pull/reset
3. checkout

WDYT @PawelLipski ?

**Comment by PawelLipski** [comment]
@mkondratek it can just be `checkout remote branch` (a branch authored by someone else, the one that you're going to review), using our `slide in` feature
