### ISSUE TITLE
Replace new base (hash presently) rebase parameter with branch name

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#579]
Somewhat related...

![image](https://user-images.githubusercontent.com/19799111/92917164-84afad00-f42e-11ea-9a89-5f111e5fa94a.png)

_Originally posted by @mkondratek in https://github.com/VirtusLab/git-machete-intellij-plugin/issues/563#issuecomment-691027255_

---

This msg looks too specific. It would be nice to show the parent branch name instead of its hash.

We cannot access and change the msg directly as it comes from `GitRebaseUtils.rebase` (git4idea).

1. Investigate the possibility of replacing commit hash with branch name
2. Implement if possible and verify resulting msg

**Comment by mkondratek** [comment]
![image](https://user-images.githubusercontent.com/19799111/92919698-410a7280-f431-11ea-9fcd-199ae0e98cdb.png)

I assume that in some cases fork point used as the `parent` (aka `upstream`) may differ from the commit pointed by the parent branch.

@PawelLipski can you confirm/decline my assumption?

**Comment by PawelLipski** [comment]
> I assume that in some cases fork point used as the parent (aka upstream) may differ from the commit pointed by the parent branch.

Yes, definitely - this will always be the case if rebasing a red-edge branch.

**Comment by PawelLipski** [comment]
Note that in case of rebases corresponding to `git machete update`, new base is always the parent branch (so we don't need to display commit hash in the notification). In case of rebases corresponding to `git machete reapply`, new base is always the fork point of the rebased branch, which might or might not be the commit pointed by the parent branch... but we don't support `reapply`-style rebases from the plugin anyway.
