### ISSUE TITLE
Branch tree rediscover after last branch deletion

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#582]
This feature (roots slide out) combined with the automatic discover leads to buggy behavior.

### Scenario (most likely not only one)
1. Have a few branches (locally and written to machete file); delete on slide out **off**
2. Slide 'Em All :guitar: Out

### Actual:
Once the last (not it is always a root) branch is deleted the whole branch tree is being rediscovered automatically

### Expected: 
TBD

_Originally posted by @mkondratek in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/577#issuecomment-692565886_

**Comment by PawelLipski** [comment]
Isn't it equivalent to #562? 🤔

**Comment by mkondratek** [comment]
yup - it's equivalent
