### ISSUE TITLE
2020.4 (or rather 2021.1): switch away from deprecated notifiers methods

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#596]
> @mkondratek there's a bunch of compat warnings for 2020.3-EAP... could you check if we can/should/must address any of them now or it can/should/must be postponed?

That is interesting... at first glance it seems like some of the `VcsNotifier`'s methods became deprecated.
Among the others there is:

![image](https://user-images.githubusercontent.com/19799111/94235863-89835f00-ff0c-11ea-84fb-d40194f4718f.png)

And one from `GitUiUtil`:

![image](https://user-images.githubusercontent.com/19799111/94236453-8b015700-ff0d-11ea-889b-8445d9f02212.png)

_Originally posted by @mkondratek in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/593#issuecomment-698760123_

**Comment by mkondratek** [comment]
All of these come from https://youtrack.jetbrains.com/issue/IDEA-244040 (added `displayId`)

**Comment by PawelLipski** [comment]
(the purpose of `displayId` btw seems to be "collecting full notifications statistics")

**Comment by PawelLipski** [comment]
Hell knows when these gonna actually be phased out... let's stick to them for as long as possible :trollface: 
I checked 2021.3 EAP, few things are gone indeed (esp. implementation of checkout has changed in git4idea a bit), but old `notify...` methods are still there, still with `@ScheduledForRemoval("2020.4")` xD
