### ISSUE TITLE
Consider suggesting a (re)discover action if .git/machete hasn't been modified for a long time

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#600]
Inspired by @xgarrett's feedback :bow:

I've erronously assumed that once a user runs the very first Discover, they aren't likely to ever need Discover again since they're gonna continuously maintain the .git/machete file themselves... but the experience shows this isn't necessarily always true.

We need to cover the cases when they use Machete for some time (typically, when having multiple PRs waiting in the queue), only to switch back to plain git in the _easier times_ and then **revisit the tool** after some time.

Possibly the solution would be to show **non-modal dialog asking whether to re-discover** if .git/machete is non-empty but hasn't been modified for some fixed time (say, 2 weeks or more?). And/or an extra button can be shown in left side toolbar.

Also, let's think if README should mention anything about that, or just FEATURES is enough.

**Comment by mkondratek** [comment]
IIRC I saw something like "startup activity" around `plugin.xml`...

To be verified but if it really exists and works as it seems then we could use it, wdyt?

**Comment by PawelLipski** [comment]
Yeah, would be nice
