### ISSUE TITLE
Checkout and rebase on detached

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#630]
![image](https://user-images.githubusercontent.com/19799111/96988115-2fce7e80-1524-11eb-964f-8afbee8ba486.png)

steps to reproduce:
1. detached state, the child branch present
2. open context menu for the child branch

expected:
checkout and rebase available

actual:
disabled dues to detached state

**Comment by PawelLipski** [comment]
Whoops :/
