### ISSUE TITLE
Add Discover to toolbar actions

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#635]
Frequent discover usage seems not to be a very useful action for ones who know how to use our plugin.
However, it can be helpful for newbies.
Let's try to add it to the toolbar.

--- 

- note that toolbar overpopulation is a danger
- we need an icon for the discover action

**Comment by PawelLipski** [comment]
Conversation with a user :poland: 

![image](https://user-images.githubusercontent.com/3383210/102201308-334c0980-3ec6-11eb-864c-2dfdf5e6c866.png)
