### ISSUE TITLE
Keyboard shortcuts not working even for actions operating on current branch

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#645]
The shortcuts can be added in IntelliJ Settings.... but nothing happens :/ Likely an expected `DataKey` like `PROJECT` is missing.

Related to https://github.com/VirtusLab/git-machete-intellij-plugin/issues/264

**Comment by MaciejG604** [comment]
The keyboard shortcuts work for me. Even the ones that work on Selected Branch - you just need to right click a branch and then press the key combination. @mkondratek, @vzmerr could you check if there's a problem in your IDEs?

**Comment by PawelLipski** [comment]
Huh indeed, works for me as well now ;D probably got fixed accidentally in the meantime (as this is issue is almost 2 years old). Closing then 🎉
