### ISSUE TITLE
Provide a tool tip for root branch

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#651]
No tool tip for root branch looks strange (like a bug) in comparision to the other (non-root) branches. 
It would be good to show a simple "everything is fine - this is a root branch" tool tip in this case. 

---
- [ ] provide a tool tip for roots
- [ ] ensure that some tooltip is being provided in the all other cases

**Comment by DcortezMeleth** [comment]
I would be happy to help with this issue.
I have even created PR already, with some simple tooltips, but if you have some ideas how to change their text for better, just let me know, as it is only suggestion.
