### ISSUE TITLE
Yellow edge but `override fork point` action disabled

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#662]
![image](https://user-images.githubusercontent.com/19799111/101917741-dbad5580-3bc8-11eb-9cc7-9e2e90d9b9e9.png)

---

[repo.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/5679809/repo.zip)

**Comment by PawelLipski** [comment]
Hmmm weird... status bar says that the branch is **out of sync** to its parent...

**Comment by PawelLipski** [comment]
Argggh ok... this is because `refactor/move-topics` is repeated in the .git/machete file :frowning_face:

```
main
  develop
    refactor/move-topics
  multiple-authors
  refactor/move-topics
  pages-metadata
```

**Comment by PawelLipski** [comment]
Still, this is very confusing, most likely the second occurrence of `refactor/move-topics` should be filtered out... lemme pull https://github.com/VirtusLab/git-machete-intellij-plugin/issues/341 under the current milestone then...

**Comment by mkondratek** [comment]
rel: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/341
