### ISSUE TITLE
Autodiscover happens prematurely

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#667]
Open a project with no .git/machete file. Notification shows up before Git Machete tab is even opened:

![image](https://user-images.githubusercontent.com/3383210/102697549-d38f8e80-4236-11eb-82e4-a1c1efb098e8.png)

This might be confusing for newcomers.

I remember we've already resolved this issue... possibly it only manifests itself on 2020.3? Or a regression happened :c

**Comment by lsereda** [comment]
It manifests itself also on 2020.1.1.
