### ISSUE TITLE
Checkout and Rebase Onto Parent rebases wrong branch if this branch is repeated in Machete File

### ISSUE THREAD

**Issue by lsereda** [VirtusLab/git-machete-intellij-plugin#685]
## Bug description
How to reproduce:
1. Create some repository (e.g. by executing this script: 
[restart.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/5820873/restart.zip)
2. Open repo using Intellij
3. Open `Git tab`
4. Execute `Open Machete File` action and copy one branch to another place in branch layout (it cannot be connected to the same root as original branch)
5. In `Git tab` open `Git Machete tab`
6. Execute `Checkout and Rebase Onto Parent` action on original branch
7. Execute `Discover Branch Layout Action`

 
### Running environment
 - Git Machete plugin version: 0.8.2
 - IDE type: Intellij
 - IDE version: 2020.1.1
 - Operating system: Linux Mint 19 Cinnamon

### Screenshots
![bug1](https://user-images.githubusercontent.com/44362374/104735711-398e0980-5742-11eb-86e0-41b5c2761459.gif)

**Comment by PawelLipski** [comment]
@lsereda thanks for reporting, it's already filed as https://github.com/VirtusLab/git-machete-intellij-plugin/issues/341 and https://github.com/VirtusLab/git-machete-intellij-plugin/issues/662 :///
