### ISSUE TITLE
Refresh from floating button updates the selected repository (not the one containing machete file)

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#696]
![image](https://user-images.githubusercontent.com/19799111/106271882-740ea080-6230-11eb-96fd-f459e7217294.png)

`uild-chain` belongs to `filter-service` repo,
the opened machete file belongs to the other one (`generator-service`)

**Comment by PawelLipski** [comment]
No longer relevant since there's no floating button/external system anymore.
