### ISSUE TITLE
Explore bugs happening in the state right after `git init`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#706]
This is a notoriously weird state of the repo:

```
➜ 22:45 /tmp/foo $ git init
Initialized empty Git repository in /tmp/foo/.git/
➜ 22:46 /tmp/foo master $ cat .git/HEAD 
ref: refs/heads/master
➜ 22:46 /tmp/foo master $ ls .git/refs/heads/
➜ 22:46 /tmp/foo master $ 
```

So HEAD points to `master`... but `master` is not even a branch yet 🤦🏻 

There's surely gonna be a bunch of bugs around this state... one that I could see is that Discover dialog shows an empty tree but still asks to Save/Save&Edit. Discover action could be just disabled in that state (and a few other actions possibly as well).

**Comment by PawelLipski** [comment]
@mkondratek can we consider this closed?

**Comment by mkondratek** [comment]
Yes. As I mentioned in the PR - now all the bugs will be consistent with the ones from IntelliJ VCS 😆
