### ISSUE TITLE
Show branch which removal (as slide out side effect) was restored

### ISSUE THREAD

**Issue by DcortezMeleth** [VirtusLab/git-machete-intellij-plugin#723]
## Bug description
More like an improvement then bug in my opinion, but it's not me how decides.
When we have untracked branch in local repository slide-out gives us a possibility to additionally this remove branch.
When we do so, Intellij pop up is presented with option to restore just removed branch.
After restoration branch remain removed from Intellij.

From one point of view that seems correct as we can treat this branch as slided out just as we wanted.
But when encountered in my scenario, when I have accidentally removed branch which was untracked not because it was merged but because it wasn't pushed yet, I had to additionally refresh machete to see branch again.

I think the main question here is: Can we somehow know that restore action was used? 
If not, there was no topic at all. But if we can, maybe it will be valuable for some users?

### Running environment
 - Git Machete plugin version 0.9.0
 - IDE type Intellij
 - IDE version 2020.03.03
 - Operating system MacOS

**Comment by PawelLipski** [comment]
Thanks for posting... lemme rephrase a bit to make sure I understand the issue: would you like to see the branch restored not only in git repository, but also in the .git/machete file as well?

Also, if it comes to the branch being (un)tracked on remote... does it matter from the PoV of restoring the branch? Does IntelliJ/plugin behave differently whether the branch is tracked on remote or not? 🤔

**Comment by DcortezMeleth** [comment]
Yup, exactly. I would like to see restored branch in git-machete graph (.git/machete file) alongside showing again in git repository.

As for the second question information about branch merged/not pushed was just to present scenario wich would benefit on such change. Nonetheless as far as I am afraid Intellij/plugin and probably git too, don't see differences between branches which where merged or not not pushed yet and act the same for both cases.

**Comment by PawelLipski** [comment]
Okay! that's a sound idea in general, definitely worth considering for UX improvement. Will probably remain queued for a bit since noone is working full-time on the plugin anymore since ~August 2020 as it reached reasonable feature-completeness... but I hope one day we'll get to this one as well :)

**Comment by mkondratek** [comment]
We decided to drop this idea.

One can easily re-slide_in a branch with slide in action or from the machete file edit.
