### ISSUE TITLE
`Reattach children` checkbox isn't clickable

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#735]
![image](https://user-images.githubusercontent.com/3383210/114279922-3c458580-9a37-11eb-9393-45972519bba0.png)

Plugin version: `0.9.1-14-SNAPSHOT+git.40d2391-dirty` (probably happens as of current `develop` as well)
IDE version: 2020.3.3

**Comment by PawelLipski** [comment]
Or is it an expected behavior? 🤔

**Comment by mkondratek** [comment]
It is expected: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/439.

We can either
- leave it as it is + try to add some explanation popup on checkbox hover
- do not enforce children reattachment 

WDYT @PawelLipski ?

**Comment by PawelLipski** [comment]
Hmmm okay so in a nutshell... under what circumstances is this checkbox clickable now? 🤔

**Comment by mkondratek** [comment]
The checkbox is clickable when
`the branch has children` && `the branch is not root`

**Comment by PawelLipski** [comment]
Okay... makes sense. Closing the issue then
