### ISSUE TITLE
`Pull branch` action is inconsistent with `git pull` wrt. fetching OTHER branches from the remote

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#752]
As noticed by @micpiotrowski, `Pull branch` action behaves in a manner INconsistent with what `git pull` does, which might surprise the users.

`git pull` by default fetches **all branches** from the remote (refspec `+refs/heads/*:refs/remotes/origin/*`, unless specified explicitly).

Our `Pull branch` action fetches **only the given branch** from the remote (refspec e.g. `+refs/heads/master:refs/remotes/origin/master`), other branches under `refs/remotes/origin/` remain unchanged.

This can be resolved either by:
1. making the behavior of `Pull action` consistent with `git pull` OR
2. displaying a relevant message that explains that behavior is different from `git pull`'s (questionable, hard to convey concisely, esp. to non-expert users).

**Comment by PawelLipski** [comment]
As time passes, I'm convinced that (1.) is a way to go.

A nuance: `com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction#lastFetchTimeMillisByRepositoryName` is now only updated when the Fetch action happens... but after this change, this should be extracted to some shared place and also updated in the Pull action.

**Comment by mkondratek** [comment]
I ve came across an interesting finding. Maybe we are not consistent with git here but we are consistent with IntelliJ :laughing: 
Anyway I see that git-way is better and I will proceed with that 

IntelliJ's "Update" branch message fyi:
![image](https://user-images.githubusercontent.com/19799111/162178684-4dd456ae-ebbc-4c0d-9efa-9e797f4b632b.png)
