### ISSUE TITLE
Tests can't run `git-machete` on Windows despite `git-machete` being available from Git Bash

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#753]
We need to debug what's the `PATH` environment variable visible from the PoV of the tests.

**Comment by Beniamin-Dolega** [comment]
| Place                                            | PATH visible                                                                                            |
| ----------------------------------- | ---------------------------------------------------------------------------- |
| Windows command line             | C:\Users\'user'\AppData\Local\Programs\Python\Python39\Scripts\    |                                   
| Git Bash                                      | C:\Users\'user'\AppData\Local\Programs\Python\Python39\Scripts\     |
| Windows Power Shell                 | C:\Users\'user'\AppData\Local\Programs\Python\Python39\Scripts\    |
| Java Program                             | C:\Users\'user'\AppData\Local\Programs\Python\Python39                  |

Also Power Shell finds the file, but is not able to execute it - opens it as a normal file instead.

**Comment by Beniamin-Dolega** [comment]
| Place                                            | Full PATH enviromant variable visible          |
| ----------------------------------- | ---------------------------------------------------------------------------- |
| Windows command line             | PATH=C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps;    |                                   
| Git Bash                                      | /c/Users/Beniamin Dolega/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Beniamin Dolega/bin:/c/Program Files/Eclipse Foundation/jdk-11.0.12.7-hotspot/bin:/c/Program Files (x86)/Razer Chroma SDK/bin:/c/Program Files/Razer Chroma SDK/bin:/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/c/Program Files/Razer/ChromaBroadcast/bin:/c/program files (x86)/razer/chromabroadcast/bin:/c/program files/razer/chromabroadcast/bin:/c/windows/system32:/c/windows:/c/windows/system32/wbem:/c/windows/system32/windowspowershell/v1.0:/c/windows/system32/openssh:/c/windows/system32/config/systemprofile/appdata/local/microsoft/windowsapps:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/cmd:/c/Users/Beniamin Dolega/AppData/Local/Programs/Python/Python39/Scripts:/c/Users/Beniamin Dolega/AppData/Local/Programs/Python/Python39:/c/Users/Beniamin Dolega/AppData/Local/Microsoft/WindowsApps:/usr/bin/vendor_perl:/usr/bin/core_perl   |
| Windows Power Shell                 | C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps;    |
| Java Program from Windows command line | C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps; |                            
| Java Program from Git Bash | C:\Users\Beniamin Dolega\bin;D:\Programy\Git\mingw64\bin;D:\Programy\Git\usr\local\bin;D:\Programy\Git\usr\bin;D:\Programy\Git\usr\bin;D:\Programy\Git\mingw64\bin;D:\Programy\Git\usr\bin;C:\Users\Beniamin Dolega\bin;C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\program files (x86)\razer\chromabroadcast\bin;C:\program files\razer\chromabroadcast\bin;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\windowspowershell\v1.0;C:\windows\system32\openssh;C:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\usr\bin\vendor_perl;D:\Programy\Git\usr\bin\core_perl                  |
| Java Program from Windows Power Shell | C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps; |
| `./gradlew backendImpl:test` in Git Bash | C:\Users\Beniamin Dolega\bin;D:\Programy\Git\mingw64\bin;D:\Programy\Git\usr\local\bin;D:\Programy\Git\usr\bin;D:\Programy\Git\usr\bin;D:\Programy\Git\mingw64\bin;D:\Programy\Git\usr\bin;C:\Users\Beniamin Dolega\bin;C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\program files (x86)\razer\chromabroadcast\bin;C:\program files\razer\chromabroadcast\bin;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\windowspowershell\v1.0;C:\windows\system32\openssh;C:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\cmd;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\Beniamin Dolega\AppData\Local\Programs\Python\Python39;C:\Users\Beniamin Dolega\AppData\Local\Microsoft\WindowsApps;D:\Programy\Git\usr\bin\vendor_perl;D:\Programy\Git\usr\bin\core_perl |

**Comment by PawelLipski** [comment]
There are still problems when running the tests depending on `git-machete` command-line tool on Windows... let's postpone this task a bit. One of the small steps to make debugging this issue easier can be #757.
