### ISSUE TITLE
`SETUP_FOR_DIVERGED_AND_OLDER_THAN` is currently stalling the script on windows. Diagnose it and revert it back.

### ISSUE THREAD

**Issue by Beniamin-Dolega** [VirtusLab/git-machete-intellij-plugin#759]
`backendImpl/src/test/java/com/virtuslab/gitmachete/backend/integration/StatusAndDiscoverIntegrationTestSuite.java:57`

Currently `SETUP_FOR_DIVERGED_AND_OLDER_THAN` is commented out, because it makes the script stall on windows. Find out why this is happening, and make the script work with that line uncommented on windows.

**Comment by PawelLipski** [comment]
Should be made obsolete by #774 (no more running `git-machete` CLI from tests)
