### ISSUE TITLE
Go Lang does not update plugin

### ISSUE THREAD

**Issue by andriesfc** [VirtusLab/git-machete-intellij-plugin#767]
## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behavior.

For more non-trivial issues, we would also appreciate if you included the following details:

### Running environment
 - Git Machete plugin version
 - IDE type [e.g. IntelliJ, PyCharm]
 - IDE version [e.g. 2020.1.4]
 - Operating system [e.g. Windows]

### Logs
Enable logging on debug level for this plugin by adding
```
binding
branchlayout
gitcore
gitmachete.backend
gitmachete.frontend.actions
gitmachete.frontend.graph
gitmachete.frontend.ui
```
to list under `Help` -> `Diagnostic Tools` -> `Debug Log Settings`.<br/>
Then reproduce a bug and attach the logs to the issue.<br/>
To find IntelliJ log file, go to `Help` -> `Show Log in Files`.

Consider placing the logs within the `details` (aka "spoiler") tags as the may be very extensive.

<details>
<summary>Logs</summary>
Logs go here
</details>

### Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

**Comment by PawelLipski** [comment]
@andriesfc thanks for reporting! could you provide some additional detail, esp. the version of the plugin FROM which you were trying to upgrade? was the newer version visible in Plugins window in GoLand? screenshots would be very useful! In the meantime, I'm gonna try and reproduce it myself...

**Comment by andriesfc** [comment]
Hi

Thank for the quick response. It is amazing

The version from which I want to upgrade is 1.0.1. I suspect the upgrade did not completely succeed. Will uninstall and reinstall as suggested.

This is the version of IntelliJ I’m using:

IntelliJ IDEA 2021.2.1 (Ultimate Edition)
Build #IU-212.5080.55, built on August 24, 2021
Licensed to Andries Spies
Subscription is active until July 25, 2022.
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: debugger.watches.in.variables=false, dart.projects.without.pubspec=true, documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.vermouthx.idea (1.12.1), com.github.b3er.idea.plugins.arc.browser (0.23), wu.seal.tool.jsontokotlin (3.7.2), com.1v0.dev.hugo-intellij-plugin (0.4.2), com.gmike.visual-studio-2019-dark (1.4), net.vektah.codeglance (1.5.4), com.jetbrains.grayTheme (1.2), Dummy Text Generator (1.2.0), com.samdark.intellij-visual-studio-code-dark-plus (2.5), to-go-struct (1.0.7), com.vecheslav.darculaSolidTheme (1.0.3), io.gitlab.zlamalp.arc-theme-idea-dark (1.0), lermitage.intellij.extratci (1.9.0.201), com.peterae86.copy (1.0.3), mobi.hsz.idea.gitignore (4.2.0), com.intellij.nativeDebug (212.5080.8), org.toml.lang (0.2.154.4085-212), com.vermouthx.xcode-theme (1.4.0), org.liamjwang.yamlconfig-idea.yamlconfig-idea (0.0.3), com.ppolivka.plugin.gitcleaner (1.1.4), com.fwdekker.randomness (2.7.2), net.antelle.intellij-xcode-dark-theme (1.2.4), Rider UI Theme Pack (0.9.3), com.ultrahob.zerolength.plugin2 (0.93), Batch Scripts Support (1.0.12), com.github.novotnyr.jwt-intellij-plugin (0.11), color.scheme.Colorful Darcula (0.3), lermitage.jetbrains.darcula.sombre (1.10.0.192), com.github.mturlo.intellij.theme.spacegray (1.4.2), com.github.chencn.yamlandprops (1.0.5), de.docs_as_co.intellij.plugin.diagramsnet (0.1.11), com.jetbrains.CyanTheme (1.2), com.github.xwsg (1.2.0), com.vecheslav.darculaDarkerTheme (1.2.0), com.wzportal.idea.tool (1.0), org.sonarlint.idea (5.2.0.35150), com.zt.json-editor (2.9.1), com.intellij.kubernetes (212.5080.55), com.github.camork.fileExpander (1.7), String Manipulation (8.15.203.000.3), io.codearte.props2yaml (1.0.2), com.remoterapp.adbremote.jsonviewer.id (0.1.1), de.timon.schelling.interesting.theme (1.3), com.wzportal.idea.tool.propertiesfilesorter (1.01), net.hexar.json2pojo (1.1.0), MavenRunHelper (4.16.212.000.0), nb-mind-map-idea (1.4.12), HyperLink (1.1.1), lermitage.intellij.extra.icons (1.61.0.203), aws.toolkit (1.31-212), PlantUML integration (5.5.1), org.asciidoctor.intellij.asciidoc (0.33.19), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), com.haulmont.jpab (5.3-212), cn.wjdghd.unique.plugin.id (0.2.5), izhangzhihao.rainbow.brackets (6.21)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**Comment by PawelLipski** [comment]
> The version from which I want to upgrade is 1.0.1.

Hmm 1.0.1 is so far the latest available version 🤔 or you were trying to update from 1.0.0 **to 1.0.1**?

**Comment by PawelLipski** [comment]
By the way, how did you get to know about this tool? ;)

**Comment by andriesfc** [comment]
I’m a bit of tech junky. So I saw it recommended in an article about nifty IntelliJ plugins for Git.

I have love-hate relationship with Git: I sometimes love it, and sometimes hate it. 🙂




Andries

**Comment by PawelLipski** [comment]
You mean this one right? :o https://dev.to/anotherdevuser/5-jetbrains-plugins-to-upgrade-the-builtin-git-support-to-the-next-level-3ojf  I only found it now 😯

**Comment by andriesfc** [comment]
Yes.  That is the one 😎

**Comment by PawelLipski** [comment]
Okay! if it comes to the issue with the update in Go Land itself, can we consider that resolved? If it recurs, I'll consider opening a ticket against Jetbrains Marketplace

**Comment by andriesfc** [comment]
I will test it tomorrow morning at the office  (it is 20h35 here), and let you know. Again thank for taking the time to look at this for me.

Regards
Andries Spies

🙏 👍

Andries

**Comment by PawelLipski** [comment]
Assuming this has been resolved!
