### ISSUE TITLE
`lastFetchTimeMillisByRepositoryName` should be updated after each pull, not just fetch (follow-up to #752)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#776]
`com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction#lastFetchTimeMillisByRepositoryName` is now only updated when the Fetch action happens... but after #775, this should be extracted to some shared place and also updated in the Pull action.

**Comment by PawelLipski** [comment]
@mkondratek can you see anything else left to do within the scope of this issue? or is it all covered on #775?

**Comment by PawelLipski** [comment]
@mkondratek bump

**Comment by mkondratek** [comment]
yup, it is resolved now. update happens in both fetch and base pull
