### ISSUE TITLE
2022.1 support

### ISSUE THREAD

**Issue by KotlinIsland** [VirtusLab/git-machete-intellij-plugin#789]
I want to try out this plugin but it doesn't support my version of Idea 😟

**Comment by PawelLipski** [comment]
Getting that sorted **n o w**!

**Comment by PawelLipski** [comment]
Btw how did you get to know about this plugin?

**Comment by KotlinIsland** [comment]
I found it ages ago by searching the market place for git plugins, but never got round to checking it out.

I saw it again recently here: https://dev.to/morrone_carlo/hidden-gems-5-jetbrains-plugins-to-boost-your-productivity-1728

I like the sound of easily making small branches, and maybe this plugin can track parent branches, which is something I desire:

https://youtrack.jetbrains.com/issue/IDEA-276070

This is the most up-voted issue in my brain of all time 😳.

**Comment by PawelLipski** [comment]
Okay! good to know that this plugin keeps getting mentioned in some outside (non-VirtusLab) blogs :)

v1.2.0 which supports IntelliJ 2022.1 has been released on GitHub: https://github.com/VirtusLab/git-machete-intellij-plugin/releases/tag/v1.2.0, you can download the plugin zip from there and install via `Settings>Plugins>(gear icon)>Install plugin from disk...`. In a few dozen hours JetBrains should also accept the submission of the update to the Marketplace so it should be downloadable "officially" 📦

**Comment by KotlinIsland** [comment]
Epic! can't wait to check it out and share it round with everyone I know.

What's your opinion of migrating your Gradle build script to be more closely aligned with the JetBrains template?
https://github.com/JetBrains/intellij-platform-plugin-template

I'd be happy to make a pr if that's a direction you would be interested in going.

**Comment by PawelLipski** [comment]
> What's your opinion of migrating your Gradle build script to be more closely aligned with the JetBrains template?

Actually... why not! that's gonna include migration to Kotlin first and foremost, right?

**Comment by KotlinIsland** [comment]
Yeah, something like this: https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/436

**Comment by PawelLipski** [comment]
Okay! I'd appreciate a contribution like that, sure ‼️

**Comment by PawelLipski** [comment]
v1.2.0 is available on JetBrains Marketplace now.
