### ISSUE TITLE
(🎁) Slide in should have auto complete for easier picking from existing branches

### ISSUE THREAD

**Issue by KotlinIsland** [VirtusLab/git-machete-intellij-plugin#791]
![image](https://user-images.githubusercontent.com/65446343/158113631-5078febb-ec8e-4077-b9f7-e7179a36f303.png)
![image](https://user-images.githubusercontent.com/65446343/158113803-ba47bf9d-8bc7-4576-a67c-e6606f85b80e.png)

Awesome plugin, can't believe I haven't been using it.

**Comment by PawelLipski** [comment]
Thanks 🎉

Makes sense indeed, same as completion in `git machete add <TAB>`... you can create a new branch with both CLI `add` and GUI `Slide In` (in which sense autocompletion makes **no** sense), but also add/slide in an existing one &mdash; where autocompletion makes sense indeed

**Comment by PawelLipski** [comment]
In general our throughput in this project is now quite limited, I was mostly focused on maintenance (keeping compatibility with the new incoming IntelliJ versions) as I have other full-time commercial project to work on... but we'll have someone full-time-ish in this project soon

**Comment by PawelLipski** [comment]
For the record, probably the corresponding `textField` in `SlideInDialog.kt` should be replaced with a use of `com.intellij.ui.TextFieldWithAutoCompletion`

**Comment by KotlinIsland** [comment]
I like the new "create branch" dialogue that replaces things like spaces with underscores automatically, "slide in" doesn't have that functionality.
