### ISSUE TITLE
(🎁) Ability to make a non-local parent branch

### ISSUE THREAD

**Issue by KotlinIsland** [VirtusLab/git-machete-intellij-plugin#792]
I don't really like having a local checkout of my parent branch (`main`). Having the parent branch be a remote branch would be my preferred workflow I think.

PS: Is this the right place to raise this? Or should it go on https://github.com/VirtusLab/git-machete?

**Comment by KotlinIsland** [comment]
I have absolutely no need for a copy of main branch to sit around and get out of date, I would rather just link the child branches directly to the `origin/main`. I want to be able to update my branch in a single click, I want a single button to make by branch up to date with `origin/main`, if not I have to update my local `main`, then update my branch.

**Comment by mkondratek** [comment]
We decided to drop this idea. 

The reasons are similar as for (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/241), so...

1. It would make things too complicated (for users). In particular sync to parent status refers to the status between local branches - in the case of the remote branch, none of the statuses is applicable; theoretically, a new status would be required.

2. Soon we will provide options (quick actions) within the machete file (https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1232) - one will be able to easily checkout the remote branch.
