### ISSUE TITLE
Does not work with git worktrees - does not autodetect branches and does not find manually entered branches

### ISSUE THREAD

**Issue by jeffjensen** [VirtusLab/git-machete-intellij-plugin#795]
## Bug description
1. Open an IntelliJ project workspace on a git worktree.
2. Machete does not autodetect the repo's branches.
    - Diagram area displays message "Provided machete file (xxxx) is empty and branch layout can't be automatically detected"
    - The "empty machete file" path points to the "gitdir" value in the .git worktree file: (gitdir value path)\machete
    - Note: .git is a file in a worktree, not a directory, containing the "gitdir" value.
3. Clicking "Discover Branch Layout..." button as an additional invocation does not discover them; displays an empty branches dialog.
4. Manually editing the machete file and adding any branches does not work.
    - Diagram area displays message "None of the branches provided by machete file (xxxx) exists within the local repository"

Would like Machete to use the machete file from the main location vs have its own, if possible.

## Running environment
 - Git Machete plugin version: 1.2.0
 - IDE type: IntelliJ
 - IDE version: Ultimate 2021.3.3
 - Operating system Windows

**Comment by PawelLipski** [comment]
Thanks for reporting, I'll try to get that sorted over the weekend. Seems related (albeit not identical) to the issue recently reported by @kgadek & resolved recently in the CLI: https://github.com/VirtusLab/git-machete/issues/360.

Out of curiosity, how did you learn about this plugin?

**Comment by jeffjensen** [comment]
> will try to get it sorted over the weekend

Thank you.


> Out of curiosity, how did you learn about this plugin?

It was mentioned in a post with some other plugins.

**Comment by PawelLipski** [comment]
Done! check v1.2.1. I'd appreciate any additional feedback, on the now-fixed worktree support or otherwise

**Comment by jeffjensen** [comment]
Works well now with my worktrees across many repos!  Thank you for making it work.
