### ISSUE TITLE
Non-Project Files Protection dialog shows up when editing .git/machete unless Open Machete File action has been executed

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#800]
## Repro

1. Open .git/machete file via Open Machete File action
2. You should be able to edit this file without any dialogs
3. Now close the project WITHOUT closing machete file
4. Reopen the project
5. Try editing machete file
6. A dialog **might** show up:

![image](https://user-images.githubusercontent.com/3383210/160415169-00f127fe-dc7e-453f-86ca-738fdaf547a8.png)

It doesn't show up under 2021.3.3, but does under 2022.1 opened via `gradle runIde`. Not sure if that's a matter of `runIde`, or rather of the IDE version.

**Comment by PawelLipski** [comment]
Reassigned for the sake of _load balancing_

**Comment by MaciejG604** [comment]
Can't reproduce this with IntelliJ 2022.1 when opening it via `./gradlew runIde`. Maybe just a Linux problem?
