### ISSUE TITLE
java.io.IOException: Creating directories for U:\.config\jgit failed

### ISSUE THREAD

**Issue by MichaelInsberg** [VirtusLab/git-machete-intellij-plugin#805]
## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.

For more non-trivial issues, we would also appreciate if you included the following details (if not filled automatically):

### Running environment
 - Git Machete plugin version - 1.2.1
 - IDE - JetBrains Rider 2021.3.3
 - Operating system - Windows 10 10.0

### IDEA - Stack trace
```
java.io.IOException: Creating directories for U:\.config\jgit failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:412)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:219)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:744)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$4(FS.java:430)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### IDEA - additional info
N/A

### Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

**Comment by PawelLipski** [comment]
For the record: JGit creates a `.config/jgit/config` file, more details under https://stackoverflow.com/questions/58074297/what-is-the-meaning-of-this-gitconfig-filesystem-section-filesystem-private

As a quick fix, if my above diagnose is correct ☝🏻, you can change the `XDG_CONFIG_HOME` env var in the system to some other directory (where your system user will have the permissions to write).

**Comment by mkondratek** [comment]
It's hard to say what's wrong without more details.

Extending @PawelLipski advice I can suggest **running IntelliJ as administrator**.

I ve been using Git Machete IntelliJ Plugin a bit on Windows but I see this one for the first time. 
I also tried to reproduce it now but no success on that.

--- 

@MichaelInsberg if you tell us more about the circumstances we probably will be able to do something.

**Comment by mkondratek** [comment]
No response for a while now. Closing.
