### ISSUE TITLE
Confirm that on Mac OS, it's Ctrl+Option+Shift+M that opens the tab (and not Cmd+...)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#813]
We've probably already checked that but I'm not sure... this shortcut is defined as:

```xml
<keyboard-shortcut keymap="$default" first-keystroke="control alt shift M" />
```

I mean, it'd be weird if `control` mapped to Cmd on Mac... but let's make sure and update the docs everywhere in the unlikely case it is indeed.

**Comment by mkondratek** [comment]
shift option command M

**Comment by mkondratek** [comment]
disconfirming

**Comment by mkondratek** [comment]
I will update README
