### ISSUE TITLE
In plugin.xml, IntelliJ warns that `GitMacheteVisibilityPredicate` is not assignable to `java.util.function.Predicate`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#814]
![image](https://user-images.githubusercontent.com/3383210/164486140-e3e6d62c-7742-41af-8856-89d5fa1bae4d.png)

`GitMacheteVisibilityPredicate` extends (via 2 other types) `com.intellij.util.Function`, which is deprecated; using `java.util.function.Function` is recommended instead.

It doesn't seem to be actually a problem as for now... let's check, however, if we can just change the implemented interface without breaking compatibility with the older versions.

**Comment by mkondratek** [comment]
It's not an issue for now. I checked and NotNullFunction is still supported (however deprecated indeed).
It has been introduced in 212.
