### ISSUE TITLE
Rebase fails due to invalid declare option (pre rebase hook)

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#828]
#mac #macos #hooks

<img width="338" alt="image" src="https://user-images.githubusercontent.com/19799111/167085565-f4cd11f3-d0c4-4942-934f-7ab513f27f36.png">

BUT
`git machete update` worked just fine

**Comment by mkondratek** [comment]
This is more urgent b/c it makes working with the project on Mac OS much less convenient (thinking about myself and @azdrojowa123 esp. 😆 ). I will take care of that!

**Comment by PawelLipski** [comment]
Whoops pls fix indeed!

**Comment by mkondratek** [comment]
It's strange. I read that the `-g` option is available since Bash 4.2. Checking the version from terminal I have 5.1.16 - and the same running `bash --version` and `echo $BASH_VERSION` (directly and within a script) with java `ProcessBuilder`. 

But still. `-g` option is not available. A switch to `eval` is a solution most likely
