### ISSUE TITLE
Create dialog to inform that current branch is not managed by plugin

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/git-machete-intellij-plugin#832]
Create some kind of dialog to inform user that current branch is not managed by plugin. Maybe create some checkbox to add this branch to plugin. Add also button to _Don't ask again_ about this issue.

**Comment by PawelLipski** [comment]
Dialog should be **non**-modal, we don't want it be intrusive.

> create some checkbox to add this branch to plugin
I'd even say, it can be button/link (rather than checkbox per se)

**Comment by mkondratek** [comment]
What's the specific scenario for this one?

1. Be on a managed branch 
2. Checkout non-managed branch (from command line / git4idea)
3. Show VcsNotification with an action to add the non-managed branch under the inferred parent. 

Is that it?

--- 

Notes:
- We need handling for no-managed root branches - where the parent cannot be inferred (I suppose).
- What if the inferred parent is different from what a user expects? The VcsNotification could have two actions (despite `Dismiss` or smth). `Accept` or `Accept and edit Machete file`
- Such a notification should take an expiration into account. I think that another checkout or Machete file edit belongs to actions that would make the notification expired (no longer valid) - probably there is more of them.

**Comment by mkondratek** [comment]
Writing it just for a log.

The topic
```
BranchChangeListener.VCS_BRANCH_CHANGED
```
is not good enough for us. I took a look into what comes to `com.intellij.openapi.vcs.BranchChangeListener#branchHasChanged(String branchName)` and I saw `HEAD`, `f47545bb46bdfe280a2f80e37925d5df6918be1f`, `build-chain^{0}` and sometimes correct result - the newly checked out branch 

I think we must rely on 
```
GitRepository.GIT_REPO_CHANGE
```
and most likely have our own implementation of branch change tracking.

**Comment by mkondratek** [comment]
The "wrong" ones are those I listed: HEAD, f47545bb46bdfe280a2f80e37925d5df6918be1f, build-chain^{0}.

**Comment by PawelLipski** [comment]
Okay... and what was expected? That none of them shows up? 🤔

**Comment by PawelLipski** [comment]
So, in a nutshell, when `VCS_BRANCH_CHANGED` is used, do we experience **false positives** (superfluous notifications) or **false negatives** (missing notifications)?

**Comment by mkondratek** [comment]
I would expect the name of a branch that I ve checked out 😆 the above ones even might refer to the same thing (the branch) but we need simply a name. 

Another thing is that the `branchHasChanged` does not cover all cases. When you change the branch from command line and then move back to IDE window the topic is not being synced (it is not triggered). On the other hand, `GitRepository.GIT_REPO_CHANGE` works in that case correctly.

**Comment by mkondratek** [comment]
It turned out that we need #1285 before this one.
