### ISSUE TITLE
Provide a check for icon paths

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#842]
As mentioned in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/823#discussion_r872975149

A compilation error would be the best but the icons are loaded dynamically. 
Even though there is no error but some strange "default" icon (or no icon).

The `Icon` is a straightforward interface (`javax.swing.Icon`) and I see no nice way to verify if the icon has been loaded correctly. 
Theoretically, we could check its height and width (which could be a good thing to do too) but that is a bit hackish.

IMHO the best solution is a bash script 🤓 
- check if paths from code and files in the directory matches 
- check if _dark versions are present 
- check if the dimensions are proper (16x16)
- check if icons used by plugin.xml are declared in MacheteIcons.java

**Comment by PawelLipski** [comment]
Actually... shouldn't it be enough to call `com.intellij.openapi.util.IconLoader#findIcon(java.lang.String, java.lang.Class<?>, java.lang.ClassLoader, com.intellij.openapi.util.IconLoader.HandleNotFound, boolean)` with `HandleNotFound#THROW_EXCEPTION` as the 4th param, instead of the current `com.intellij.openapi.util.IconLoader#getIcon(java.lang.String, java.lang.Class<?>)` from `icons.MacheteIcons#loadIcon`?

**Comment by PawelLipski** [comment]
Also, since this will a **runtime** and not build-time check, pls verify that a typo in file name will actually lead to a failure in UI tests

**Comment by mkondratek** [comment]
I tried this:
```java
public static @Nullable Icon findIcon(@NotNull String path, @NotNull Class<?> aClass, boolean deferUrlResolve, boolean strict) {
  return findIcon(path, aClass, aClass.getClassLoader(), strict ? HandleNotFound.THROW_EXCEPTION : HandleNotFound.IGNORE, deferUrlResolve);
}
```
Setting `strict=true` (and `defer=true` which is required to go to the more promising if else branch) does not work - I saw no exception.

**Comment by mkondratek** [comment]
```java
private static Icon loadIcon(String path) {
  Icon icon = IconLoader.findIcon(path, MacheteIcons.class, /* deferUrlResolve */ true, /* strict */ true);
  if (icon instanceof IconLoader.CachedImageIcon) {
    IconLoader.CachedImageIcon cachedImageIcon = (IconLoader.CachedImageIcon) icon;
    if (cachedImageIcon.getRealIcon().equals(IconLoader.CachedImageIcon.EMPTY_ICON)) {
      throw new Error("icon missing!");
    }
  }
  assert icon != null;
  return icon;
}
```

Smth like that will result in an error indeed but it gives ide internal error only (no UI test failure).

**Comment by PawelLipski** [comment]
☹️
