### ISSUE TITLE
An error is displayed when the pulled branch has been removed from the remote

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#845]
I haven't taken a screenshot... but IIRC a message `can't fast-forward to refs/remotes/origin/...` is displayed, which makes sense: `git fetch --prune` removes the local mirror of the remote branch and well, a fast-forward of the local branch to remote branch can't happen.

The behavior is okay, just it would be better to display a more user-friendly message in this case, like `The remote branch has been removed, cannot pull anymore`

**Comment by mkondratek** [comment]
probably the `<html></html>` tag wrapping is needed to use `<br/>` tag. At least I see it for `action.GitMachete.BaseResetBranchToRemoteAction.info-dialog.message`
