### ISSUE TITLE
Inconsistent context menu item for Merge Parent Into

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#848]
`Checkout and Rebase Onto Parent` but `Checkout Selected Branch And Merge Parent Into It`

I requested it myself, for the sake of clarity... but I already don't like it 😅 It looks really awkward in context menu.

Maybe change the latter into:

```
Checkout And Merge With Parent
```

This is less precise (after all, it could be interpreted as "merge this branch into parent")... but putting it close to Rebase makes the purpose quite clear.

Or alternatively! How about changing both captions:
```
Checkout and Sync to Parent by Rebase
Checkout and Sync to Parent by Merge
```
❓
This way it's clear that both actions achieve the same goal ⚽

**Comment by mkondratek** [comment]
Good points made here and I agree with your concerns about the first option. 
I would go for the second - it reflects the common thing; making the branch to be in sync.
And we can provide a more extensive explanation of git operation going under the hood in the action description.

**Comment by mkondratek** [comment]
NOTE: Changing the action names will result with inconsistency to the scenarios and recordings from README (and the other places probably).
