### ISSUE TITLE
Update the scenario recordings 

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#850]
After https://github.com/VirtusLab/git-machete-intellij-plugin/issues/421, https://github.com/VirtusLab/git-machete-intellij-plugin/issues/737, https://github.com/VirtusLab/git-machete-intellij-plugin/issues/793 (and probably others) the look of our plugin changed. Now it's inconsistent (or incomplete) with readme, docs, and **scenario recordings** in particular.

What needs an update
- [x] scenario recordings (README.md, and [plugin overview ](https://plugins.jetbrains.com/plugin/14221-git-machete))
- [x] scenario descriptions (README.md)
- [x] Getting Started description at plugin overview page (docs/plugins.jetbrains.com/general_usage_instructions.html)
- [x] docs/features.md ( I forgot we have that one Xd )
- [x] [the blog post](https://medium.com/virtuslab/take-a-look-at-your-repository-from-a-new-perspective-with-git-machete-plugin-e2e5e4197a0b) if possible 

can you see anything else?

**Comment by PawelLipski** [comment]
Recordings to be coded into UI tests, for easier reproducibility

**Comment by PawelLipski** [comment]
...and recordings to be actually updated in v2.0.1, so as not to block the release; everything else (the text changes) to be shipped with v2.0.0.

**Comment by mkondratek** [comment]
Referring to https://plugins.jetbrains.com/plugin/14221-git-machete:
~General Usage Instructions~ Getting Started section **updated** (I think they renamed that section - I ll piggyback that rename to the file somewhere)
Sample status png **updated**
gifs **not updated** yet

**Comment by PawelLipski** [comment]
Further work to be done within v2.0.1, moving the issue there

**Comment by mkondratek** [comment]
blog post updated: https://medium.com/virtuslab/take-a-look-at-your-repository-from-a-new-perspective-with-git-machete-plugin-e2e5e4197a0b

thats all - closing
