### ISSUE TITLE
Create job for automatically checking if new EAP has appeared

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/git-machete-intellij-plugin#853]
Connected with https://github.com/VirtusLab/git-machete-intellij-plugin/issues/794. 
Basically the idea is to create some cyclic job (hope that circleCI has the ability to do such things) which run task `updateEapBuildNumber`, and if new EAP is available create some PR with this change.

**Comment by PawelLipski** [comment]
For PR creation, check the recently removed piece of code from CircleCI config: https://github.com/VirtusLab/git-machete-intellij-plugin/commit/7da97d28783d8e91d925d195007d3cc5f04bb352
