### ISSUE TITLE
Change bundle `format` into extension method

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#855]
From discussion on https://github.com/VirtusLab/git-machete-intellij-plugin/issues/852.

@mkondratek :
> I ve quickly tried this (getString & format together):
> 
> ```java
>   public static String getFmtStr(@PropertyKey(resourceBundle = BUNDLE) String key, String... args) {
>     return format(instance.getString(key), args);
>   }
> ```

@PawelLipski :
> > I ve quickly tried this (getString & format together):
> 
> The question is whether we can still have compile-time checking of properties done by https://checkerframework.org/manual/#i18n-formatter-checker ... it looks that `@I18nMakeFormat` won't work on such `getFmtStr` method ☹️

> Although! I still think some hacks can be done with Lombok's [`ExtensionMethod`](https://projectlombok.org/features/experimental/ExtensionMethod), like `getString(...).fmt(..., ...)` which would expand to `format(getString(...), ..., ...)` but be more readable, while not impeding `I18nFormatterChecker`'s operations

**Comment by PawelLipski** [comment]
Oh! I've just opened more generic #854 😅

**Comment by mkondratek** [comment]
ok!
