### ISSUE TITLE
What are the capabilities associated with the token used to upload plugins?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#868]
Can it just be used to uploading new version of the plugin and nothing else?

If it has the full capabilities of the owner's JetBrains account... it might be better to create a service account (analogue of @git-machete-bot in GitHub) and use its token for plugin uploads instead

**Comment by azdrojowa123** [comment]
I did not find a specific answer in the documentation so asked about this topic IntelliJ support. They told me that this token is used for authentication on plugin storage and doesn't provide access to other services.

**Comment by PawelLipski** [comment]
Closing then!
