### ISSUE TITLE
Establish a channel to share the current beta version with the outside teams

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#89]
Possible mimic the setting of https://github.com/VirtusLab/contextbuddy - a public repo with a link to download (maybe just commit the zip directly in the repo as for now); or maybe even better - use **Github Pages**, to be activated under repo settings

**Comment by PawelLipski** [comment]
Not a concern anymore since we decided the repo is public anyway.

**Comment by mkondratek** [comment]
https://plugins.jetbrains.com/plugin/14221-git-machete
