### ISSUE TITLE
The last item on context menu is unselectable if it is placed beyond window border

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#890]
This is currently `Show in Git Log`, used to be `Slide out` until recently. I can hover over the penultimate item and then reach the last item by keyboard arrows. Hovering over the last item doesn't make it selected if this item is located beyond window border.

I suppose that's a GNOME-specific problem... pls verify if it happens on Macs.

Funnily enough, I've never observed the similar https://github.com/VirtusLab/git-machete-intellij-plugin/issues/683 problem on Linux/GNOME.

![image](https://user-images.githubusercontent.com/3383210/171465361-2c17a9c8-d8de-428a-8ff3-6a39d6b5e379.png)

Probably adding a separator at the end on Linuxes (or even on all systems for simplicity) might be a solution.

**Comment by mkondratek** [comment]
https://user-images.githubusercontent.com/19799111/171587572-749e951a-20f3-4c97-9746-72abdc343e14.mov

**Comment by mkondratek** [comment]
We decided to drop this issue.

1. It does not occure on macOS and seems to be Gnome related.
2. One can easily wrok it out.
