### ISSUE TITLE
File a bug against projectlombok/lombok for the apparent lack of `@ExtensionMethod` support for interfaces

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#892]
Let's try using `Try.sequence` as extension method on, say, `GitCoreRepository`:

```java
return List.narrow(result.sequence().getOrElseThrow(GitCoreException::getOrWrap).toList().sortBy(b -> b.getName()));
```

If such a class like below is added to the package and then listed in `@ExtensionMethod` of `GitCoreRepository`:

```java
package com.virtuslab.gitcore.impl.jgit;

import io.vavr.collection.Seq;
import io.vavr.control.Try;

public class Ext {
  static <T> Try<Seq<T>> sequence(Iterable<? extends Try<? extends T>> values) {
    return Try.sequence(values);
  }
}
```

then `gitCore:jGit` compiles. But an attempt to use `io.vavr.control.Try` directly in `@ExtensionMethod` ends up in compilation error (`sequence` method not found).

Would be nice to create a minimal repro (is it about interfaces? or maybe just **generic methods** in interfaces?) in a separate project, and file a bug against Lombok (unless already opened, check both opened AND closed issues). At least Lombok should mention the case of interfaces in their docs for `@ExtensionMethod`, if for whatever reason the support isn't possible.

**Comment by MaciejG604** [comment]
I prepared a repository that shows the problem:
https://github.com/MaciejG604/lombok-bug-report

You can take a look, I will link it in the PR for lombok.

**Comment by MaciejG604** [comment]
DONE - https://github.com/projectlombok/lombok/issues/3228
