### ISSUE TITLE
Remove `machete-pre-rebase` hook from this repo

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#898]
Ofc the support for the hook itself in the plugin should stay as is.

Plus update the docs accordingly.

**Comment by mkondratek** [comment]
why?

**Comment by PawelLipski** [comment]
Needless complication, in hindsight we don't really need to rewrite the versions back on every commit with `git filter-branch`... just bumping on the last one is enough (esp. given that all these commits will typically be squashed at the end anyway).

The worst that can happen is a non-monotonic sequence of versions in git history... but still, `git describe` will display the version properly, based on git tags.

**Comment by PawelLipski** [comment]
Done on #904
