### ISSUE TITLE
Investigate possibilities of speeding up/turning off indexing in UI tests

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#899]
Indexing takes time. 
That affects both local test execution (potentially scenario execution) and CI test runs.

Let's check if we can turn it off/ speed up somehow.

This may be worth to read: https://blog.jetbrains.com/idea/2020/04/lightedit-mode/

**Comment by PawelLipski** [comment]
TBD if Git Machete tab is even available in this Light Mode 😅 but maybe there's a different way to turn off indexing indeed... as it's completely useless for our UI tests (WTF is even getting indexed? 😯 would be good to check first)

**Comment by mkondratek** [comment]
yeah, I check light mode - it's a dead end. too primitive 😞 but there can be another way

**Comment by mkondratek** [comment]
I tried marking all sources as `Excluded` - the times were very similar but the plugin (the whole VCS) is not working. that's another dead end 😞

**Comment by PawelLipski** [comment]
Rel, I've just got an email from JetBrains newsletter about 2022.3 EAP:

![image](https://user-images.githubusercontent.com/3383210/194369825-13e22887-46a0-45ad-b0d9-184edf462211.png)

Which might affect us positively in UI tests (haven't checked so far though)

**Comment by mkondratek** [comment]
oh, if it's true it's nice

**Comment by mkondratek** [comment]
We decided to drop this issue.

1. We can only depend on what Jet Brains offers to us.
2. The times are not so bad.
