### ISSUE TITLE
Are the files under `scripts/` automatically recognized as Shell scripts by IntelliJ?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#902]
I remember that I needed to override their file types manually 🤔

Add `.sh` extension to them if they aren't recognized automatically

**Comment by wils81ouwehand** [comment]
Mensen ik ben geen raket geleerde!!!

**Comment by PawelLipski** [comment]
Wanna pick this one up then? 🧑‍🔬

**Comment by MaciejG604** [comment]
Fix provided by new IntelliJ feature - file type association, which can be opened like this:
![image](https://user-images.githubusercontent.com/61919032/177518512-92252803-bb92-4654-9b12-8c8218ce87b1.png)
![image](https://user-images.githubusercontent.com/61919032/177518629-b124e92c-8672-4361-aef4-3bf8e003baa6.png)

Thus by setting the underlined option all scripts with hashbangs will be associated with correct file type.
No further work is needed.
