### ISSUE TITLE
Wouldn't the fast-forward icon be more intuitive if it pointed backwards (to the left)?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#906]
I mean... technically it's parent that fast-forwarded (i.e. parent is _moving_, child is _staying_)... but from intuitive PoV, the user is fast-forward merging the child to parent. In other words, the intuitive direction of the merge is from child to parent.

TBH despite I'm all to well familiar with what happens under the hood... I still catch myself thinking over why the arrow points to the right and not to the left :trollface: 

@azdrojowa123 @mkondratek pls speak your minds

**Comment by mkondratek** [comment]
No strong feelings - we can even rotate like that ![image](https://user-images.githubusercontent.com/19799111/172470285-54b3dbdb-3dcc-417b-a974-4bdd20219027.png) Xd but I would rather ask someone from the outside of the project just to confirm your thinking

**Comment by mkondratek** [comment]
We decided to drop this idea.

To be precise the direction is different from Git Log (^), Git Machete (v), and the general convention (>) POV. Let's stick to what it is.
