### ISSUE TITLE
`createNotification` is scheduled for removal in a future version 

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/git-machete-intellij-plugin#913]
Check if it is possible (compatible with previous versions) to change calling `createNotification` from `NotificationGroup.kt` (which is deprecated) to `createNotification` from `VcsNotifier.java`

**Comment by PawelLipski** [comment]
While you're at this... could you check with `runPluginVerifier` what's the minimal IntelliJ version to support `createNotification` from `VcsNotifier`? so that this issue can be linked to the adequate `Drop support for IntelliJ ...` issue
