### ISSUE TITLE
Migrate logic from some shell scripts to `GitMacheteBundlePropertiesTestSuite`

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/git-machete-intellij-plugin#915]
Idea to migrate logic from shell scripts: 

- `scripts/enforce-properties-single-quotes-consistent-with-format-elements`
- `scripts/prohibit-properties-double-quote-wrapping`

To `GitMacheteBundlePropertiesTestSuite`. 
After rewriting logic from shell scripts to this test suite, scripts should be removed.

**Comment by PawelLipski** [comment]
Also, within the scope of this task, JUnit test results can be exported for `frontend:base` module in the CI (as they are for other modules currently)
