### ISSUE TITLE
Add extra issue types to issue template

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#961]
As in https://github.com/VirtusLab/git-machete/issues/522

**Comment by vzmerr** [comment]
What about?
- Feature request
- crash report
- other issue
- help/support

**Comment by mkondratek** [comment]
**Feature request** for sure as we have received a few of them for now.

I would rather avoid creating very detailed templates for bugs/issues/crashes/help to keep the reporting process extremely easy and clear. I can imagine that someone sees so many options, and gets confused about what to pick, and eventually abandons the idea of opening an issue. 

That's my personal opinion ofc and I am open to discussion.

**Comment by vzmerr** [comment]
So I would say just 
- bug report
- feature request
- help/support

In simple templates?

**Comment by mkondratek** [comment]
For me, it's the most reasonable

**Comment by vzmerr** [comment]
It seems that the easiest way to add them is to follow [these instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). But I don't have access to the `settings` of the repository.

**Comment by mkondratek** [comment]
oh me too. @PawelLipski we want more rights ✊

**Comment by PawelLipski** [comment]
Huh I can grant you more rights 😅 buuuuuuut isn't it possible to configure these issue types by adding files to `.github/ISSUE_TEMPLATE/`? 🤔 I'd rather keep as much of the configuration "anchored" in the code (as opposed to "unanchored" configuration somewhere deep in GitHub settings)

**Comment by vzmerr** [comment]
it just happens that using the GitHub predefined templates, also adds them to `.github/ISSUE_TEMPLATE/` 🙃

**Comment by mkondratek** [comment]
bump

**Comment by PawelLipski** [comment]
❓

**Comment by mkondratek** [comment]
I was just opening some feature request and recalled that we had this issue. I don't know if it could actually help xd
