### ISSUE TITLE
`skipNonExistentBranches_...` UI test failing: unexpected branch in the refreshed table model, due to autodiscover

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#979]
That's something new at least 😆

Build: https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5562/workflows/b837b1b9-1e2f-4d5c-8d7f-2e7090729a98/jobs/5867

```
com.virtuslab.gitmachete.uitest.UITestSuite > skipNonExistentBranches_toggleListingCommits_slideOutRoot FAILED
    java.lang.AssertionError: expected:<List(allow-ownership-link, build-chain, call-ws, develop, hotfix/add-trigger, master, update-icons)> but was:<ArraySeq(allow-ownership-link, build-chain, call-ws, develop, drop-constraint, hotfix/add-trigger, master, update-icons)>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.virtuslab.gitmachete.uitest.UITestSuite.skipNonExistentBranches_toggleListingCommits_slideOutRoot(UITestSuite.scala:88)
```

It's strange... `drop-constraint` appears in refreshed model.
But it's not added to machete file in the first place, nor later by overwrite. 

The only way I see it is that the branch has been automatically rediscovered but that should not take place by refresh, am I right?
Or do you see any other options?

**Comment by PawelLipski** [comment]
Huh indeed... I can only think of autodiscover 🤔 actually... can you add some extra logging in autodiscover code, such that will be visible in UI test logs in the CI? so that we have extra clues once this occurs again

**Comment by mkondratek** [comment]
We've got a proof:

![image](https://user-images.githubusercontent.com/19799111/177980637-d089a8a7-82e7-4123-8901-cf8250caa4cf.png)

**Comment by mkondratek** [comment]
again: https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5660/workflows/14ee6947-b657-40a2-bcaf-98506b09f1a4/jobs/5974

**Comment by mkondratek** [comment]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6059/workflows/a72a622d-3d40-45b0-bcac-a6ab9345d2eb/jobs/6398/parallel-runs/0/steps/0-109

I used good old `println` (along with logger debug) - autodiscover happens indeed!

**Comment by PawelLipski** [comment]
Okay... and out of curiosity, since autodiscover happens... I suppose that the value of `isMacheteFilePresent` in `com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable#refreshModel(git4idea.repo.GitRepository, com.virtuslab.gitmachete.backend.api.IGitMacheteRepositorySnapshot, java.lang.Runnable)` is `true`, so we fall into `gitMacheteRepositorySnapshot.getSkippedBranchNames().isEmpty()` case right?

**Comment by mkondratek** [comment]
I have the other suspect. The logic seems to be good however there is some race condition (I think I found the place but now the tests pass xd).

Another interesting observation - looking quickly into the CI runs it happens that this error occurs only on the first build run 🤣 every time I rerun workflow from CI it passes. It seems that the CI must be triggered by push xd

**Comment by PawelLipski** [comment]
> I think I found the place

Pls share the knowledge! so as to increase this particular issue's _bus factor_ 😅

**Comment by mkondratek** [comment]
I am looking around `GitMacheteRepositoryUpdateBackgroundable` - I am wondering if the next lines
```
        gitRepository.getMacheteFile().forEach(macheteFile -> VfsUtil.markDirtyAndRefresh(/* async */ true,
            /* recursive */ false, /* reloadChildren */ false, macheteFile));
```
can be executed before the backgroundable finishes 🤔

**Comment by PawelLipski** [comment]
Whoops indeed they can hmm 🤔 would it make sense to pack this `forEach` into `doRefreshModel` callback? Although the callback is to be executed on UI thread... not sure if reasonable for `VfsUtil.markDirtyAndRefresh` (although this looks like a quick operation)

**Comment by mkondratek** [comment]
But still - markDirtyAndRefresh takes `async` param...  we must be careful

**Comment by mkondratek** [comment]
But indeed - I managed to reproduce a situation where `markDirty` **line** executes before `refreshModel` ([proof](https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6213/workflows/e2d55906-0cb7-4d17-85fb-3515691e7f73/jobs/6574))

However the build did not fail - that might be because the markDirty performs in async so it still could be on time

**Comment by mkondratek** [comment]
My questions for now.

What is `VfsUtil.markDirtyAndRefresh`? What it does? Can we do it sync?
Does it matter if we force some order  b/w`VfsUtil.markDirtyAndRefresh` and `refreshModel`?

**Comment by mkondratek** [comment]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6227/workflows/5f0d2733-5e72-4a35-8845-74ce7abe31ca/jobs/6588/steps **FAILED** 🎉

**Comment by PawelLipski** [comment]
> What is VfsUtil.markDirtyAndRefresh? What it does?

Hmm this is coming from https://github.com/VirtusLab/git-machete-intellij-plugin/pull/586, which is a fix for https://github.com/VirtusLab/git-machete-intellij-plugin/issues/568 🤔 

>  Can we do it sync? Does it matter if we force some order b/wVfsUtil.markDirtyAndRefresh and refreshModel?

YOLO, let's try ;D you can do a quick time measurements to check how heavy an operation it is &mdash; whether it can be fired on UI thread (if it's going to simplify anything)

**Comment by LukaszKontowski** [comment]
for the record: another similar failed build https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6597/workflows/5f5a375b-1cde-4007-b3ab-21a799acc5f8/jobs/6979

**Comment by PawelLipski** [comment]
Okay... @mkondratek could you post all the results that you've collected so far (in case the task is to be handed over)?

**Comment by mkondratek** [comment]
The above suspicions can be true.

In particular I ve tried to  `Thread.sleep(500)` in `doRefreshModel` and enforce the failure but it did not work.

I ve looked into the logs that we now store as an artifact and I see GitMacheteRepositoryDiscoverer running once. 
On the other hand `GitMacheteRepositoryUpdateBackgroundable - Queuing graph table refresh onto the UI` appears 5 times.
