### ISSUE TITLE
Use Gradle toolchain instead of `if (JavaVersion.current() != JavaVersion.VERSION_11)`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#983]
https://docs.gradle.org/current/userguide/toolchains.html

**Comment by salmansharifov** [comment]
@PawelLipski Can I take this issue?

**Comment by PawelLipski** [comment]
Sure! pls open a PR from your fork to `develop` branch in this project

**Comment by PawelLipski** [comment]
Hey @salmansharifov, are you going to work on that?

**Comment by PawelLipski** [comment]
TBD if it still makes sense now that the build supports both Java 11 and 17 though

**Comment by PawelLipski** [comment]
Might be revisited when Java 11 support is dropped (#859)

**Comment by PawelLipski** [comment]
Plugins for IntelliJ 2022.3 must be built on JDK 17 anyway (https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1201)
